### ISSUE TITLE
Cannot start on Window 10

### ISSUE THREAD

**Issue by JokerQyou** [xupefei/QuickLook#1]
As shown in the screenshot. System version: Windows 10 x64 1607 (internal version 14394.1066), software version v0.1.1 downloaded from Github releases.

![image](https://cloud.githubusercontent.com/assets/1465267/25600949/cdbd81d4-2f1a-11e7-8441-6bc21f0debf2.png)

**Comment by Congee** [comment]
same issue

**Comment by xupefei** [comment]
You may try to "unblock" the .zip file you downloaded BEFORE extracting it.
Details here: http://www.chilkatforum.com/questions/8260/could-not-load-assembly-operation-not-supported-exception-from-hresult-0x80131515

**Comment by H-Yedda** [comment]
cannot open on windows 10

**Comment by fakerqu** [comment]
Quicklook won't work when you use it in explorer with clover

**Comment by fakerqu** [comment]
Quicklook cannot open a .doc file with password

**Comment by domoto1982** [comment]
> As shown in the screenshot. System version: Windows 10 x64 1607 (internal version 14394.1066), software version v0.1.1 downloaded from Github releases.
> 
> ![image](https://cloud.githubusercontent.com/assets/1465267/25600949/cdbd81d4-2f1a-11e7-8441-6bc21f0debf2.png)
