### ISSUE TITLE
Test on Windows 10S

### ISSUE THREAD

**Issue by xupefei** [xupefei/QuickLook#102]
Please take the following action
Please submit an update by 10/26/2017 to keep your app in the Store. If you need more time, unpublish your app before the due date and you can republish it when you're ready. Otherwise, if we unpublish your app, you’ll need to contact reportapp@microsoft.com before you can submit your app update; include your app ID so we can act quickly.

App Policies: 10.1.2.1 Inaccurate Functionality: Windows 10S
Notes To Developer
Your app doesn't work on Windows 10 S and the application terminates without notice to the user. Apps that don’t work on Windows 10 S must support the graceful shutdown.
 
Steps to reproduce
1. Launch the app
2. Check if the app is running in the background in the toolbar.
3. Launch Windows Explorer
4. Choose a file and press SPACE, as per Notes to Certification
5. Notice that there is no response from the action
6. Check if the app is running in the background in the toolbar
7. Run the mouse over the app icon
8. Notice that the icon disappears.

Please be sure to test your app for Windows 10 S: https://docs.microsoft.com/windows/uwp/porting/desktop-to-uwp-test-windows-s
Tested Devices: Windows 10 Desktop

**Comment by Fingalzzz** [comment]
May I know when will the WIN10 UWP version come back? Is it in your recent working list?

**Comment by xupefei** [comment]
Sorry but I cant give any ETA at the moment. I am rather busy now but I hope I can find some time next month.

cheers,
Paddy
