### ISSUE TITLE
[bug] 窗体左移

### ISSUE THREAD

**Issue by Cologler** [xupefei/QuickLook#105]
在文件列表中按 ↓ 或 ↑ 会使预览窗体左移

**Comment by xupefei** [comment]
给个屏幕录像？

cheers,
Paddy

From: cologler
Sent: 27 October 2017 15:39
To: xupefei/QuickLook
Cc: Subscribed
Subject: [xupefei/QuickLook] [bug] 窗体左移 (#105)

在文件列表中按 ↓ 或 ↑ 会使预览窗体左移

**Comment by Cologler** [comment]
![ts](https://user-images.githubusercontent.com/10906962/32104677-115e426a-bb58-11e7-972a-f2ad5802b66f.gif)

逐渐挡住日期

**Comment by xupefei** [comment]
我找了一些图片试了试，并没有发现这个现象。
方便的话，可以把这些图片打包给我吗？
Mail: xupaddy#@#gmail#@#com

**Comment by Cologler** [comment]
这个是所有图片都有的，不是特定图片。
而且这个问题只在图片预览中出现，没有在其它预览（比如文件夹）中看到。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xupefei** [comment]
我是用了一些尺寸相同的照片测试的，没有发现这种现象。所以我怀疑是图片的问题……

![video_2017-10-28_231329](https://user-images.githubusercontent.com/1687847/32138114-49f6f69c-bc36-11e7-820d-5eb2d57446e0.gif)

**Comment by Cologler** [comment]
我的图片也全是相同分辨率的，840x1200。我的是 portable 版，不过和这个可能没啥关系。

**Comment by xupefei** [comment]
你可以下载[最新的 Nightly 版](https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts)试试看。

**Comment by Cologler** [comment]
上述版本有依旧有这个问题。。。
话说，切换选取的时候会重置窗体位置吗？
还有，为什么只有图片的预览才会出现这个问题......


获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xupefei** [comment]
你屏幕分辨率多少？DPI是100%吗？

cheers,
Paddy

**Comment by Cologler** [comment]
分辨率是标准 1080P，缩放是 100%。

**Comment by Cologler** [comment]
调试了下，在这个位置：

https://github.com/xupefei/QuickLook/blob/master/QuickLook/MainWindowTransparent.xaml.cs#L272

每次 call 的时候 `this.Left` 会减 1。

应该是 `WindowHelper.MoveWindow()` 中 `double` 转 pixel 时候导致的失真。
试着改成宽高差距小于 2px 时不调用 `MoveWindow()` 就好了。

话说为什么要用 win32 的方法去移动窗体而不用 wpf 的方法呢？

**Comment by xupefei** [comment]
把 TransformToPixels 里的 (int) 改成四舍五入试试看？

WPF不能同时修改 Left 和 Top，而分别修改会造成窗口两次刷新。

cheers,
Paddy

**Comment by Cologler** [comment]
还有 `QuickLook.NativeMethods.GetCurrentSelection()` 中为什么会有这样一段代码？：

``` cs
// communicate with COM in a separate thread
Task.Run(() =>
{
    sb = new StringBuilder(MaxPath);
    if (App.Is64Bit)
        GetCurrentSelectionNative_64(sb);
    else
        GetCurrentSelectionNative_32(sb);
}).Wait();
```

改成

``` cs
sb = new StringBuilder(MaxPath);
if (App.Is64Bit)
    GetCurrentSelectionNative_64(sb);
else
    GetCurrentSelectionNative_32(sb);
```

不会更快些吗？

**Comment by xupefei** [comment]
你可以试试，会报错 :-)
连接 COM 需要 STA 线程。

cheers,
Paddy

**Comment by Cologler** [comment]
嗯，四舍五入 `Math.Round()` 就好了。

你是用 VS 编译的吗？我这里编译时 ps1 生成的 gitversion 提示版本字符串不合法……

**Comment by xupefei** [comment]
手动执行一下 Scripts/update-version.ps1 试试看。
应该生成类似 1.2.3.4-abcdef 的东西。

**Comment by xupefei** [comment]
PS：愿意的话你可以提个 PR。

**Comment by Cologler** [comment]
我知道为啥我编译不了了……我只 clone 了深度 1，所以没有 tag……
