### ISSUE TITLE
Pressing spacebar in Explorer starts a search

### ISSUE THREAD

**Issue by Thisismai** [xupefei/QuickLook#107]
Hi there,

As title says, when I'm in Windows Explorer, have any file selected and press spacebar, the search bar in the top right is activated instead of QuickLook.

Spacebar and QuickLook works on desktop.

Running Windows 10 Pro 1709

Running Quick Look 0.3.1 appx version

I'm guessing this is inherently a Windows 10 action that is overriding QuickLook?

I really like the potential of this app, coming form Seer which seems to no longer be developed. Thanks for developing it!

**Comment by xupefei** [comment]
Change the action when typing in an Explorer window as follows:

![image](https://user-images.githubusercontent.com/1687847/32142655-41ae0386-bca4-11e7-9082-3f9523799085.png)


BTW: Seer is still in development but [as a paid software](http://1218.io/seer/order.html).

**Comment by Thisismai** [comment]
Thanks for the really fast reply!

That solved the issue.

Wow, the Fluent Design acrylic material is a really nice touch. You should redesign Explorer ; )

I did purchase Seer but haven't had it installed for quite a while, it was quite slow and had a hard time previewing certain files. When you release this I'll be sure to purchase.

Many thanks!

**Comment by xupefei** [comment]
Glad to hear that!

> When you release this I'll be sure to purchase.

QuickLook is a free and open-source software. No need to throw your money on 😜

**Comment by Thisismai** [comment]
Is there a way to tip? xD

**Comment by xupefei** [comment]
Thank you, but I do not accept any donation at the moment :P

**Comment by DawnLck** [comment]
Thanks!

**Comment by ikhanrahi** [comment]
> Change the action when typing in an Explorer window to follows:
> 
> ![image](https://user-images.githubusercontent.com/1687847/32142655-41ae0386-bca4-11e7-9082-3f9523799085.png)
> 
> BTW: Seer is still in development but [as a paid software](http://1218.io/seer/order.html).

Thanks Dude...you just save my day 💃
