### ISSUE TITLE
How do you uninstall ?  

### ISSUE THREAD

**Issue by funderarock** [xupefei/QuickLook#109]
I installed .0.3.1 and I can't really figure out how to uninstall it.  Please advise.

**Comment by xupefei** [comment]
You may uninstall it from Control panel/Uninstall programs or Setting/Apps.

cheers,
Paddy

From: funderarock
Sent: 01 November 2017 19:46
To: xupefei/QuickLook
Cc: Subscribed
Subject: [xupefei/QuickLook] How do you uninstall ? (#109)

I installed .0.3.1 and I can't really figure out how to uninstall it. Please advise.

**Comment by funderarock** [comment]
first place I tried,  it's not listing in the windows 10 control panel / programs and features.

**Comment by xupefei** [comment]
Perhaps you are using the portable version?

The app are in `C:\Users\you_user_name\AppData\Local\Programs` folder, and configuration is in `C:\Users\you_user_name\AppData\Local\pooi.moe` folder. You can delete them maunally.
