### ISSUE TITLE
Fail to show compressed GIF images

### ISSUE THREAD

**Issue by Small-Ku** [xupefei/QuickLook#110]
無法顯示已壓縮的GIF檔案
Attached some samples
![field](https://user-images.githubusercontent.com/16464896/32317545-0d2fb9b2-bfef-11e7-86e5-e5f03b567db6.gif)
![index](https://user-images.githubusercontent.com/16464896/32317547-0d79f7de-bfef-11e7-93c5-801859318619.gif)
https://1drv.ms/f/s!AksON-mfu8BY0TZfRzP3O_eszbG_

**Comment by xupefei** [comment]
This issue has been fixed in #78 and will be released along with the next version.
You can also try it now by downloading a nightly build from https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts.
