### ISSUE TITLE
Video Preview not working

### ISSUE THREAD

**Issue by emannxx** [xupefei/QuickLook#113]
Hello, 
I installed the new release (v 0.3.2) today and there's a major bug affecting video previewing. 
I installed the .msi package on a Windows 10 v. 1709 (Fall Creators Update) x64 and it's not possible at all to preview any video file. I tried previewing a .mp4 (h264) video file as well as a .mkv to no avail. Nothing happens, not even an error message.
When trying so preview any other file after trying to preview a video, Quicklook also does not respond, I had to force close the app process through task manager because the icon on the system tray also stops working. 

Should you need any more information (or help reproducing this bug), contact me asap and I'll be glad to help.

**Comment by xupefei** [comment]
Go to `install_folder\Plugins\VideoViewer\FFmpeg` folder. There should be have a `ffprobe.exe` file. Can you run it in command prompt?

**Comment by emannxx** [comment]
Yes, here's the output:
![image](https://user-images.githubusercontent.com/6955982/32440183-f8cf82ce-c2e9-11e7-9faf-6eec59adebe2.png)

**Comment by xupefei** [comment]
Strange. How about `FFprobe.exe "<any_video_file>"`?

**Comment by emannxx** [comment]
![image](https://user-images.githubusercontent.com/6955982/32440279-62d1acd8-c2ea-11e7-94f5-3bf96b82ccbf.png)

**Comment by xupefei** [comment]
Seems the probe is working normally.
Can you debug the project by setting a breakpoint here:https://github.com/xupefei/QuickLook/blob/master/QuickLook.Plugin/QuickLook.Plugin.VideoViewer/Plugin.cs#L72
Does the program hang here?

**Comment by emannxx** [comment]
I don't have the project configured on this machine, I'll have to set it up (might take a while since VS isn't updated). I'll post the results here ASAP.

**Comment by xupefei** [comment]
It may takes some time since I have updated the Windows SDK recently.
Can you alternatively provide me a sample video file so i can have a try?

**Comment by emannxx** [comment]
Just sent you and email with a link. 😉

**Comment by xupefei** [comment]
If the Big Buck Bunny works for you, then it may be related to the HW acceleration. 
I have made a new plugin w/o it. Could you try it?

**Comment by emannxx** [comment]
I'm having trouble trying to compile QL. I'm always getting this git-related error. Do you know how can I fix this? (Already have git installed) 
![image](https://user-images.githubusercontent.com/6955982/32441751-cedc2b28-c2f0-11e7-8b56-d2929fd19b29.png)

**Comment by xupefei** [comment]
You should enable local execution of powershelgl scripts. The command is here: https://superuser.com/questions/106360/how-to-enable-execution-of-powershell-scripts <https://superuser.com/questions/106360/how-to-enable-execution-of-powershell-scripts>
cheers,
Paddy

**Comment by emannxx** [comment]
Thanks.
Here's the info on the breakpoint. I also tried using the updated VideoViewer you sent, didn't work.
As you see in the screeshot below, I set two breakpoints, however, the second one is never reached.  Execution goes into `new FFProbe` and never runs the `probe.HasVideo()`.

![image](https://user-images.githubusercontent.com/6955982/32442450-6342ff10-c2f3-11e7-9e60-3529ad39d69a.png)

**Comment by xupefei** [comment]
Thanks for helping locate the problem!
Could you move into the FFprobe class, and test if this line is reached: https://github.com/xupefei/QuickLook/blob/master/QuickLook.Plugin/QuickLook.Plugin.VideoViewer/ffmpeg/FFprobe.cs#L54

1. If no, can you execute `ffprobe.exe -v quiet -print_format xml -show_streams -show_format "<something.mkv>"` in command prompt?

2. If (1) successes, try comment this line `p.StartInfo.StandardOutputEncoding = Encoding.UTF8;` and debug again.

**Comment by emannxx** [comment]
Execution (on FFprobe) hits the breakpoint, however, commenting `p.StartInfo.StandardOutputEncoding = Encoding.UTF8;` doesn't change the behaviour. Nothing still happens.

**Comment by xupefei** [comment]
How about the next line? Does line 56 or 59 be reached?

**Comment by xupefei** [comment]
Okay, I think I have figured out the problem.
Could you try swap Line 54 and 56, i.e., 
```
result = p.StandardOutput.ReadToEnd();
p.WaitForExit();
```

**Comment by emannxx** [comment]
Yep, that did the trick. It's working fine now :)

**Comment by xupefei** [comment]
Thanks for the feedback! I will fix it now.

**Comment by emannxx** [comment]
You're welcome! Glad I could help :)
