### ISSUE TITLE
WAV 24bits are not played

### ISSUE THREAD

**Issue by ashokleyland** [xupefei/QuickLook#115]
Hi,

latest version is not playing 24bits wav audio files.
16bits wav are playing good.
0.3.1 version was ok

Thanks

**Comment by xupefei** [comment]
Example please?

**Comment by xupefei** [comment]
Thanks for your sample file, I confirm that I can reproduce this issue, which is from upstream `FFME`.
I have reported this issue to them as unosquare/ffmediaelement#110. Waiting for their comments.

**Comment by xupefei** [comment]
This issue is now fixed by the upstream. I will also fix it soon.
