### ISSUE TITLE
有数个问题，一并问了。

### ISSUE THREAD

**Issue by TaicEart** [xupefei/QuickLook#116]
如果必须一 issues 一问，就请告诉我，然后只回复第1问，我会把第2问及以下分拆为多个 issues 的。
均使用的3.2.1版，在 Win8.1（中文64位）下。

## 图片不能即时预览？
并不是特例，所有图片均是如此。以[250px-Erf_taiji.svg.png 这个图片](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Erf_taiji.svg/250px-Erf_taiji.svg.png)为例，从按下<kbd>空格</kbd>，转圈半周后显示，此过程约耗时1秒，预览图片速度和预览视频仿佛。不清楚是否只有我是这样，相比 Mac 上的流利按<kbd>→</kbd>换图，这种等待比较痛苦。

## 似乎缺乏缩放归位或了解缩放程度的操作？
<kbd>Ctrl</kbd>+<kbd>滚轮</kbd>缩放后就不知道缩放到什么程度了。看不出是90%还是95%……
- 无论是像浏览器那样<kbd>Ctrl</kbd>+<kbd>+/-</kbd>
- 还是在滚轮操作中显示百分比数值（滚轮停止则渐隐）

我都可以返回原缩放比。当然<kbd>Ctrl</kbd>+<kbd>0</kbd>直接100%最好了。

## 预览其实可以显示更大一点。
打开壁纸大图时发现预览并不会充满屏幕（也就是说被缩小了），要是这个占屏比有参数可调就好了。

## 连续按<kbd>→</kbd>换图时预览窗口仍维持第1张尺幅。
预览长宽比悬殊的一包图发现的。例如微博长图<kbd>→</kbd>壁纸，壁纸横向缩得没法看了。

## 不能被 MacType 渲染。
MacType 有认到 QuickLook.exe、QuickLook.WoW64HookHelper.exe，但完全不能渲染。

## 看不到托盘图标。
在 win8.1 上有一个问题：托盘图标是全白的，因此在收入隐藏托盘时在白色背景上完全看不到。可以单独给 16px 加上类似默认图标的勾边吗？如果有源文件，我或可以改画一个并作成ico。

**Comment by xupefei** [comment]
1. 我觉得是你机器配置的问题。你提供的这张图片在我这里是瞬间打开的，大概只有 0.1-0.2s 载入时间。
2. 缩放操作现在的确缺少指示。接下来我要加一个上去。
3. 屏占比的问题，如果占用空间太大的话会影响其他操作，甚至挡住后面的资源管理器窗口。一般不会只开一个预览窗口的。
4. 换图时预览窗口仍维持第1张尺幅：特意为之。关闭窗口再打开就会重新计算尺寸。
5. MacType 的问题：WPF 采用 GPU 加速所以无法被渲染。听说有个 DirectWrite补丁可以强行开启渲染，但我没用过不知道具体行不行。
6. 字体文件的预览目前还没空搞……
7. 托盘图标的问题刚刚已经修复，在 win10 之前的系统上全部采用彩色版图标。

**Comment by bestvow** [comment]
psd文件预览
100M以内的打开非常块
200M以上的打开非常久

**Comment by xupefei** [comment]
PSD 会自动存缩略图的，显示应该很快才对。我没有这么大的PSD。能给个例子吗？
cheers,
Paddy

**Comment by TaicEart** [comment]
总算爬上来了。其实屏占比与是否维持尺幅这2项希望是可调的。主要是连续预览一文件夹图时，遇到比例不同要换键按2下空格再返回<kbd>→</kbd>略为不便。

（大概不是配置，某s软件可以瞬间打开预览，且流畅换图。那么我先更新一下再反馈）

**Comment by xupefei** [comment]
具体你这是什么问题我也不清楚了，因为即使在我的SP4 Core m3 开省电模式的情况下，预览也是秒开。

AppVeyor 的和 Github 的区别只有签名。另外，你可以从 Windows Store 下载。
