### ISSUE TITLE
我发现了一个 bug

### ISSUE THREAD

**Issue by ChromeBing** [xupefei/QuickLook#117]
预览回收站内的文件导致崩溃，请在回收站内禁止使用。
Preview in the recycle bin file, leading to collapse, it is prohibited to use in the recycle bin, please.

**Comment by NBOOK** [comment]
商店版0.2.5，并没有你所说的问题，回收站里的文件可正常预览

**Comment by ChromeBing** [comment]
我是用的是 0.3.2.1

**Comment by xupefei** [comment]
![image](https://user-images.githubusercontent.com/1687847/32593405-7567489c-c530-11e7-81c9-473d7a16938b.png)
不崩啊。

**Comment by ChromeBing** [comment]
那就不清楚了，不影响使用

**Comment by sxul** [comment]
是不是你在移动设备之类的删除的文件 …不过那样应该不会显示出来啊

**Comment by ChromeBing** [comment]
不是的哦
