### ISSUE TITLE
文本或者md文件预览能支持搜索就完美了

### ISSUE THREAD

**Issue by qianjigit** [xupefei/QuickLook#119]
感谢作者大大能够开源这么优秀的软件，提个建议：

> 预览文字较多内容时，无法直接搜索，对于直接想确认点资料内容来说，滚动翻查或者再打开都比较影响效率。
> 而预览后，能够搜索定位，使用上来说，只是查询的文件基本都不用打开了。

**Comment by xupefei** [comment]
但是 QuickLook 只是个让你迅速看一看文件内容的工具啊。

**Comment by sxul** [comment]
不如直接用everything的高级搜索

**Comment by DawnLck** [comment]
我有点明白他的想法了，主要是文字较多的文件吧，既不想打开doc再搜索，又不想预览时一行行找过去（这样的确不如用office或者wps打开再弄），嗯，搜索这个功能我觉得可以加一下的，针对txt或者doc，能快速定位关键词还是很有用的。

**Comment by dddreams** [comment]
必须很有用啊，希望添加
