### ISSUE TITLE
Wrong preview location

### ISSUE THREAD

**Issue by gigios** [xupefei/QuickLook#12]
I have tried the last release (0.1.8) and I have a problem with the preview visualization.
After the start of the application the first visualization of the preview is correct, at the center of the screen (+/-), if I try to reopen again the preview, now the location is completely to the right side. Only a small part is visible.
This is the example of the visualization of the README.md file, more than half part of the window is outside the screen.
![immagine](https://cloud.githubusercontent.com/assets/8749627/26140792/fcc5a302-3ad8-11e7-80ef-5ff671a228f4.png)

I don't know if the problem could be related the usage of two monitors (I'm using two monitors and the main is the right monitor).

**Comment by xupefei** [comment]
Yes, it is related to dual-monitor in https://github.com/xupefei/QuickLook/blob/master/QuickLook/MainWindow.xaml.cs#L65-L66.

I will try and try to fix it.
