### ISSUE TITLE
html文件预览功能

### ISSUE THREAD

**Issue by NevenLeung** [xupefei/QuickLook#123]
我知道QuickLook，对于html文件的预览是浏览器的渲染之后的效果，但对于像下面这样的template file，其实我不想看到浏览器显示的效果，我只想看看里面是怎么写的。当然，这个我打开editor，就可以完成这一步，但我的editor打开有点慢，我只是想看一下里面的写法而已，所以我想QuickLook能帮我完成这个。

![image](https://user-images.githubusercontent.com/18048923/32763645-dc5f2b00-c93b-11e7-846e-f6f01862e9bf.png)

改进的建议：

- 不改变现有功能的前提下(个人觉得html要浏览网页内容，还是得用浏览器，html文件可能会有网页跳转，而对于web开发，还会用到调试功能)，可以增加一个toggle的按钮，来切换原始文本跟渲染效果
- 如果是有toggle按钮，软件可以记住toggle的选项，方便下次使用

ps：不知道是我的电脑渣，还是什么原因，对于第一次打开的文件类型，QuickLook显示时不是很迅速，大概要两秒吧，内存占用也不大，2、30M吧

谢谢！！

**Comment by sxul** [comment]
其实我也觉得…html文件不如直接显示带着色的源码，或者加个开关可以切换源码和预览

**Comment by xupefei** [comment]
The further discussion goes into https://github.com/xupefei/QuickLook/issues/132.
