### ISSUE TITLE
ePub

### ISSUE THREAD

**Issue by xupefei** [xupefei/QuickLook#125]

**Comment by Cologler** [comment]
epub 我也考虑过，但是 epub 是个 zip 文件，解压可能导致 cpu 占用率上升（我遇上过 50M 的书）。如果插件接口是 async Task 加载并且有 CancellationToken 作为参数可能会好很多（在频繁切换状态下运行取消解压中的状态）。

**Comment by KrasnayaPloshchad** [comment]
自从 LibreOffice 开始支持导出 EPUB 以来，这个功能还是很有用的，希望早日实现。

**Comment by xupefei** [comment]
Implemented in PR #297.
