### ISSUE TITLE
视频字幕显示有问题

### ISSUE THREAD

**Issue by xhml** [xupefei/QuickLook#127]
这是QuickLook预览字幕:
![这是QuickLook预览字幕](https://user-images.githubusercontent.com/14312777/32874298-38caf450-cacc-11e7-917e-3bebe29067c9.png)
这是用系统自带播放器字幕展示效果:
![这是用系统自带播放器](https://user-images.githubusercontent.com/14312777/32874301-3ec8137e-cacc-11e7-810b-50f5239ecd10.png)
这个视频封装了多个字幕,不知是不是有关系
![系统播放器字幕选择](https://user-images.githubusercontent.com/14312777/32874331-7d01b0fa-cacc-11e7-98a0-4edd23b4a21e.png)

版本号:win10商店最新v0.3.2.1

**Comment by xupefei** [comment]
FFmpeg好像不支持ass字幕。晚上我在测试一下。

**Comment by xupefei** [comment]
最新的Nightly版应该修好了。试试看?

**Comment by RichieChow** [comment]
thanks，nightly版对ass支持相当完整，不管对内挂还是外挂，特效还是图形代码均能正常显示，不过该如何切换多个字幕呢，hevc似乎没有硬解（七代酷睿应该是支持的，虽然我正儿八经播放视频不开硬解，但作为一个预览软件感觉还是开硬解省点资源好），音量好像又不能记住上次设置，每次预览默认50%了

**Comment by xupefei** [comment]
我已经开了 DXVA2 硬解。
播放 HEVC 的时候，任务管理器里 GPU 的 Video Decode 有使用率吗？
![image](https://user-images.githubusercontent.com/1687847/35472269-cddf9812-0374-11e8-8eec-d57e128ad8e8.png)

**Comment by RichieChow** [comment]
hevc的视频解码一直0%，但有时打开时会出现瞬间的负载之后就一直是0（随机发生，暂未找到规律
