### ISSUE TITLE
apng显示有问题

### ISSUE THREAD

**Issue by xhml** [xupefei/QuickLook#128]
很令人惊讶的是这个软件居然支持apng的播放(并且并不支持动态webp的播放 XD)
但是它的显示看上去有一点问题.
这是预览的结果:
![snipaste_2017-11-16_12-53-56](https://user-images.githubusercontent.com/14312777/32874490-85725dec-cacd-11e7-9b55-cedc32ffe48f.png)
这是原图:
![snipaste_2017-11-16_12-53-56](http://littlesvr.ca/apng/images/GenevaDrive.png)
[这是图片来源](http://littlesvr.ca/apng/gif_apng_webp1.html)

版本号:win10商店最新v0.3.2.1

**Comment by xupefei** [comment]
应该是我在解码器里把 disposal flag 写错了。
