### ISSUE TITLE
部分视频会很均匀的卡顿

### ISSUE THREAD

**Issue by xhml** [xupefei/QuickLook#129]
![snipaste_2017-11-16_13-02-51](https://user-images.githubusercontent.com/14312777/32874678-bedd070c-cace-11e7-8f02-1fc47dbf1462.png)
以上是视频信息(potplayer和系统自带电影和电视均不卡顿),QuickLook会一直以一种很均匀的卡顿来播放(不是卡一下然后流畅一下,而是一直在卡,一直卡着向前播放)
当然,QuickLook只是用来瞟一眼而不能用一个播放器的角度来衡量,所以我只是提供一下issues,如果修复需要投入过多精力就没必要了
版本号:win10商店最新v0.3.2.1

最后:新版ui太漂亮了

**Comment by xupefei** [comment]
#115.

现有的 FFmpeg 组件解码速度跟不上，在播放高清音频／视频的时候解码速度赶不上播放速度。
我已经提了一个 issue，目前作者还没回信。

**Comment by xhml** [comment]
@xupefei 是已知bug是最好的,不然我还打算想办法给你截取出一段视频样本来呢(好多视频分割软件都会改变编码,所以我正为此苦恼怎么展示给你)

**Comment by xupefei** [comment]
上游已经把这个bug修好了，我这里很快就会修。

**Comment by xupefei** [comment]
Fixed.
