### ISSUE TITLE
预览word会崩溃

### ISSUE THREAD

**Issue by panyuz** [xupefei/QuickLook#131]
预览word会崩溃。日志在哪里找？我上传下
win10 office 365

**Comment by xupefei** [comment]
不用了，这是已知问题。然而我还没想好要怎么搞……

**Comment by Tespera** [comment]
我安装的是Office 2016专业版，预览Word文档时打开有点慢，比Excel文件和PDF文件要慢很多。但是并没有崩溃，最终还是会打开的。

**Comment by xupefei** [comment]
The further discussion goes into #94.
