### ISSUE TITLE
Quick Look 启动约3秒后崩溃

### ISSUE THREAD

**Issue by yudenzel** [xupefei/QuickLook#133]
Windows 10, 64bit, OS Build 14393.1884

启动后弹出消息框，消息框消失后程序崩溃退出。
![image](https://user-images.githubusercontent.com/4387218/33076783-ac8b467a-cf08-11e7-999a-77ca7e4f0f58.png)

![image](https://user-images.githubusercontent.com/4387218/33076473-c902831e-cf07-11e7-9aae-d79265bbe5a5.png)

![image](https://user-images.githubusercontent.com/4387218/33076593-18ac60b0-cf08-11e7-900f-ee2106d1352a.png)

**Comment by xupefei** [comment]
使用便携版请记得在解压前解锁 <https://github.com/xupefei/QuickLook/issues/1>。
https://github.com/xupefei/QuickLook/issues/1 <https://github.com/xupefei/QuickLook/issues/1>

cheers,
Paddy

**Comment by yudenzel** [comment]
orz...
好神奇。
最开始装的时候v3.2也没解锁，就可以用，所以没往那个地方想。。。

@xupefei  谢谢了。
