### ISSUE TITLE
抽象出插件接口

### ISSUE THREAD

**Issue by Cologler** [xupefei/QuickLook#135]
现在是 QuickLook.Plugin.* 引用了 QuickLook，所以只编辑插件的话以就要编译 QuickLook。
有个问题是我编译不了 QuickLook 依赖的 QuickLook.Native （C++）。

如果能把 QuickLook.Plugin.* 引用的 QuickLook 的部分抽象出来，比如 QuickLook.PluginInterfaces，那我就只需要编译 C# 部分就好了。

**Comment by xupefei** [comment]
你可以直接把QuickLook.exe复制过去，加到引用里……

cheers,
Paddy

From: cologler
Sent: 24 November 2017 00:24
To: xupefei/QuickLook
Cc: Subscribed
Subject: [xupefei/QuickLook] 抽象出插件接口 (#135)

现在是 QuickLook.Plugin.* 引用了 QuickLook，所以只编辑插件的话以就要编译 QuickLook。
有个问题是我编译不了 QuickLook 依赖的 QuickLook.Native （C++）。
如果能把 QuickLook.Plugin.* 引用的 QuickLook 的部分抽象出来，比如 QuickLook.PluginInterfaces，那我就只需要编译 C# 部分就好了。

**Comment by Cologler** [comment]
这样每次修改 proj 文件后 commit 都要修改引用

**Comment by xupefei** [comment]
Uncheck these two then it will be fine.

cheers,
Paddy

**Comment by Cologler** [comment]
我上次编译时就是这样编译的，所以提了这个 issue……😂

**Comment by xupefei** [comment]
把ContextObject剥离出来比想象中要麻烦……这周应该能搞定

**Comment by xupefei** [comment]
Fixed.
