### ISSUE TITLE
[BUG?] 语法高亮

### ISSUE THREAD

**Issue by Cologler** [xupefei/QuickLook#136]
AvalonEdit 看起来是支持 python 的（Python-Mode.xshd），但实际上 .py 文件没有语法高亮。

**Comment by xupefei** [comment]
![image](https://user-images.githubusercontent.com/1687847/33204879-8caee9ea-d10d-11e7-9f84-3a9ad2bf9da8.png)

包含 py 高亮的版本没有在 NuGet 放出来。
