### ISSUE TITLE
[Feature request] how about a fluent design preview window?

### ISSUE THREAD

**Issue by suxpert** [xupefei/QuickLook#139]
It'll be so cool. XD

**Comment by xupefei** [comment]
But now it already is. Any comments?

**Comment by suxpert** [comment]
This is quicklook UWP:
![quicklook_window](https://user-images.githubusercontent.com/1191414/33415022-0a424b84-d5cf-11e7-8038-01dd134eede2.png)

And this is calc UWP:
![calc_window](https://user-images.githubusercontent.com/1191414/33415027-0e0aa9c8-d5cf-11e7-8d30-41272e9eb4af.png)

Can not see though the title bar of quicklook. I expect at least the title bar should be like Edge. If the whole preview window is transparent like calc, it will be much cooler.

**Comment by xupefei** [comment]
Such semi-transparent window is limited to UWP. QuickLook, however, is a "traditional" app.

**Comment by suxpert** [comment]
But AFAIK, Edge is not a traditional win32 app either, why can Edge have such a title bar?

**Comment by xupefei** [comment]
I mean, a "traditional" app will not have such semi-transparent titlebar. Edge, hovever, is a UWP which is not "traditional".

**Comment by xupefei** [comment]
I tried to implement a "fake" semi-transparent effect in commit a969687b7bc6aeb5f440193b35a32b83e962e1c6. Please have a try and give any feedback.

**Comment by Scarwoman** [comment]
commit a969687 looks amazing! This is how I think quicklook should look. Though the preview of word documents is now incorrect. 
![schermopname 98](https://user-images.githubusercontent.com/32339475/34906772-13435ff8-f874-11e7-99ad-3e4f07f92648.png)

**Comment by xupefei** [comment]
Thanks for the feedback :)

I am planning to rewrite the Office previewing module in the near future. It should solve this problem.

**Comment by xupefei** [comment]
Moved to #94.
