### ISSUE TITLE
Previewing a large tar.gz file costs too much time

### ISSUE THREAD

**Issue by suxpert** [xupefei/QuickLook#140]
The app froze for several minutes before contains were shown.

**Comment by xupefei** [comment]
The .tar file does not have an index structure thus a full scan is required to enumerate all files inside.
However, the noticeable waiting time can be reduced by async loading. I will do it in the future.

**Comment by xupefei** [comment]
Fixed in 97b749e64f43c166110ef0984d9b6cdc0cdf7369.
