### ISSUE TITLE
Windows 10 1709, QuickLook 0.3.2.1 cannot open

### ISSUE THREAD

**Issue by DawnLck** [xupefei/QuickLook#144]
Found it not work when i use in the Windows 10 1709.
It looks fine when i use at my desktop,but not works well when i come into any folder in the computer.
When i keydown the space, it will turn to search field at the left-top.
So i think ,maybe somthing wrong in this system 1709.

**Comment by xupefei** [comment]
Please refer to #107.

**Comment by lukaszjablonski** [comment]
I still have this problem in the version 4.5.0 (QuickLook won't start in any folder in File Explorer but works for items on the Desktop) despite following #107 (i.e.: "File Explorer Options" > "View" > "Select the typed item in the view" is enabled)
