### ISSUE TITLE
Windows 10 1709, QuickLook 0.3.2.1 Doesn't start.

### ISSUE THREAD

**Issue by jstrellner** [xupefei/QuickLook#146]
I have uninstalled it and reinstalled it several times.  After double clicking to start the app, it thinks for a second and then doesn't do anything.  I do not get a tray icon, and I can not press space to preview the file from the desktop or in Explorer.

It did work initially when i started it, but since then it has stopped.  Are there any error logs or anything that I can provide you?

**Comment by xupefei** [comment]
There should have some records in the Event Viewer.
By the way, have you tried [unlock it](https://github.com/xupefei/QuickLook/issues/1)?

**Comment by jstrellner** [comment]
I see several errors that look like the attached below. I did not try the unlock it, since I installed via the MSI.

[error.log](https://github.com/xupefei/QuickLook/files/1531268/error.log)

**Comment by xupefei** [comment]
There is a problem in your configuration file. Could you upload it here to me so I can have a look?

The file is C:\Users\joel\AppData\Local\pooi.moe\QuickLook.exe_StrongName_n5ult4xbcexpf12uxwafhsslpdggmeld\0.3.2.1\user.config

Then you can delete this file and thereafter QuickLook should back to life.

cheers,
Paddy

**Comment by jstrellner** [comment]
Thanks Paddy.  Here you go: [user.config.txt](https://github.com/xupefei/QuickLook/files/1535364/user.config.txt)

I deleted that file and it started back up. Thanks! Looks like my original file had been 0'd out... not sure how that could have happened, especially since the replaced file is XML.

Happy to poke around elsewhere if it'll help figure out what could have happened.

**Comment by xupefei** [comment]
Fixed in 2fda049c266f7d112b087f4aa84a31251673198b.

Thank you!
