### ISSUE TITLE
[Plugin.HtmlViewer] Issue with user selection

### ISSUE THREAD

**Issue by ARL64** [xupefei/QuickLook#148]
I think this picture explain it well.

![user-select-issue](https://user-images.githubusercontent.com/837109/33653284-e62bc7d2-da6c-11e7-88ca-07f0521ae44c.png)

So in css using ```user-select: none;``` the element is not selectable, but with built-in WebBrowser of Plugin.HtmlViewer the element can be selectable. In this example the line numbers.

**Comment by xupefei** [comment]
The Html Viewer employs system IE browser which is really bad. Switching to WebKit (Blink) will add another 100MB to the QuickLook package. Therefore please live with it ...

**Comment by Rictusempra** [comment]
@xupefei You need servo.
（手动滑稽）
