### ISSUE TITLE
希望选择文件时也可以进行预览

### ISSUE THREAD

**Issue by Glavor** [xupefei/QuickLook#149]
![20171207001635](https://user-images.githubusercontent.com/32591808/33672048-313a7ec2-dae4-11e7-9bce-471e5a75b055.png)
如果选择文件时也可以预览会方便许多，尤其是选图片时。如果可以的话希望后续可以支持。

**Comment by xupefei** [comment]
很久以前安装版已经支持了。商店版不支持而已。

cheers,
Paddy

From: Glavor
Sent: 06 December 2017 18:26
To: xupefei/QuickLook
Cc: Subscribed
Subject: [xupefei/QuickLook] 希望选择文件时也可以进行预览 (#149)


如果选择文件时也可以预览会方便许多，尤其是选图片时。如果可以的话希望后续可以支持。
