### ISSUE TITLE
无法识别图片的色彩空间

### ISSUE THREAD

**Issue by YangXuran** [xupefei/QuickLook#150]
预览Psd,tiff文件时很多时候都不是sRGB色彩空间，但是依然按照sRGB处理，导致颜色不正确

**Comment by xupefei** [comment]
能给个例子吗？我修复的时候用来测试。

**Comment by YangXuran** [comment]
我生成了一张ProPhoto色彩空间的图片（主要是为了效果夸张一些），Photoshop打开的效果如右，QuickLook效果如左。所有的图片在使用非sRGB色域时均会出现这样的问题，直接丢弃颜色配置。因为我经常使用QuickLook预览这些文件所以发现有这个问题，并不影响大多数用户的使用。

![tim 20171207175505](https://user-images.githubusercontent.com/11170802/33709833-a7343790-db79-11e7-9fa2-f5991f04668c.png)



[test.zip](https://github.com/xupefei/QuickLook/files/1538588/test.zip)
