### ISSUE TITLE
在Total Commander中使用时窗口焦点的问题

### ISSUE THREAD

**Issue by okey3m** [xupefei/QuickLook#151]
使用的0.3.2.1版，Total Commander是9.0a版，在TC中无论绑定F3还是F4，弹出QuickLook的窗口之后，当前活动窗口仍然是Total Commander窗口，无法直接进行键盘操作，特别是无法直接用ESC键关闭QuickLook窗口，不知道可否增加一个设置，打开后直接激活QuickLook窗口为当前活动窗口？

**Comment by xupefei** [comment]
是的，特意为之。再按一下你设置的热键就会关闭预览。

**Comment by songxianpeng** [comment]
@xupefei 这样和原生的预览操作习惯不同，比如复制文本内容或者图片放大之类的操作需要用鼠标，还有就是zip预览时无法获得焦点并且窗口在TC后无法看到，能改进或者给出设置选项么
