### ISSUE TITLE
预览图标时，出现提示failed to preview xxxx

### ISSUE THREAD

**Issue by calors** [xupefei/QuickLook#153]
RT。。。实际能正常预览，但是提示无法预览。png 格式 300*300像素。
小的图标正常预览，无提示。

**Comment by xupefei** [comment]
给个图标我试试？

**Comment by calors** [comment]
给一个~  ![bugzilla](https://user-images.githubusercontent.com/11407631/34397695-49d29dea-ebb3-11e7-9abc-fa1f4f6ea797.png)

**Comment by xupefei** [comment]
你这个图片其实是个 JPG 而不是 PNG，因为文件头有 “JFIF” 字样。
