### ISSUE TITLE
第三方资源管理器调用quicklook时，第二次调用是关闭quicklook窗口

### ISSUE THREAD

**Issue by MaiTestarossa** [xupefei/QuickLook#162]
在total commander中，把外部查看器设为quicklook后
以及在xyplorer中添加脚本`run """C:\QuickLook.exe"" ""<curitem>""";`
首次运行成功显示，第二次执行该命令就变成关闭，必须再执行一次。

因为quicklook无法监视这些第三方资源管理器的 `selected item change` 事件，无法随着资源管理器内文件的切换而自动切换预览，妥协的方法就是每次想要预览一个文件执行一次`QuickLook.exe "C:\path\to\your\file.txt"`，但每次首次运行成功后，第二次执行该命令就变成关闭quicklook，必须再执行一次。

能否增加命令行选项或者另一个exe文件，设置成每次打开该exe覆盖之前的窗口而不是执行关闭动作？

**Comment by xupefei** [comment]
选定另一个文件按F3，预览是直接关闭还是切换？

**Comment by MaiTestarossa** [comment]
关闭
第一个文件选中-->F3-->QuickLook被打开
此时选定另一个文件-->F3-->QuickLook被关闭
再次F3-->QuickLook被打开

**Comment by xupefei** [comment]
应该没问题了。再试试看？
