### ISSUE TITLE
预览视频文件时显示的缩略图图片比例显示怪异

### ISSUE THREAD

**Issue by dearanswer** [xupefei/QuickLook#163]
明明是16:9的视频，显示的缩略图比例是1:1，望优化视频文件缩略图显示的效果

**Comment by xupefei** [comment]
啥缩略图？视频文件不应该直接播放了么?

**Comment by dearanswer** [comment]
没直接播放

**Comment by xupefei** [comment]
什么格式的？

**Comment by dearanswer** [comment]
ts和tp格式

**Comment by xupefei** [comment]
修好了。等会儿Nightly版自动编译完成后，新版应该能自动播放了。

**Comment by dearanswer** [comment]
好的，谢谢

**Comment by dearanswer** [comment]
请问什么时候发布新版？

**Comment by xupefei** [comment]
还有很多问题需要解决。
你可以先用着 [Nightly](https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts) 版。

**Comment by dearanswer** [comment]
已经使用Nightly 版了，发现ts.tp格式文件的预览窗口非常小，而其他视频格式的预览窗口大小就挺舒服的，烦请再优化下
