### ISSUE TITLE
你好,我反应一个改进项,一个BUG

### ISSUE THREAD

**Issue by abxialiang** [xupefei/QuickLook#165]
改进:
当文件为".lnk"快捷方式时,显示它的目标文件是否更合理?

bug:
包含特殊字符的文件无法打开,如下
รักเธอไม่มีวันหยุด - อ้อน เกวลิน [MV].mp4

**Comment by Rictusempra** [comment]
GBK编码？

**Comment by xupefei** [comment]
https://github.com/xupefei/QuickLook/issues/120 和 https://github.com/xupefei/QuickLook/issues/152 已经报告了这两个问题 :)
