### ISSUE TITLE
Feature Request: Transport overlay outside of Video instead of inside

### ISSUE THREAD

**Issue by piotrnikov** [xupefei/QuickLook#166]
Hi!
First of all thank you for a great program!!! Coming from osx this app is invaluable!!
I have just two tiny requests if at all possible. I work a lot with animated formats (gifs, mp4, ...), and I noticed that Quicklook (Win64) flashed the name of the file and the transport overlay (play/Pause...) for a couple of milliseconds before disappearing, over the actual video. My request is this:
. Could there be an option to leave this overlay on, and to keep it outside of the actual animated file (not actually over the file but outside like a frame)? 
The info frame actually stays on with the other files (jpgs, pdfs,...). It's distracting having this frame pop up and disappear over video files... 
. Also could there be an option to loop the file (basically go back to the start and play in loop)?
Thanks so much again for a great piece of software and all the best!

Piotr

**Comment by xupefei** [comment]
I also feel the overlays are annoying. Will make them hidden by default.

**Comment by piotrnikov** [comment]
Hey!
Sorry to ask again, but has this been done in the latest builds? I'm not seeing it here...
Just asking :)
I have also a couple of more thoughts (that is if you need more!):
. I think the ovelay should be present all the time actually (osx style), and not overlay the actual video but be outside the actual frame. I think that's what's really confusing (to me).
. I really miss a looping function (button?). I know that it's not an option in osx but it'd be really cool by default to have whatever Gifs of video loop.
Thanks again and sorry for being so insistent :)
I love Quicklook!!

Piotr
