### ISSUE TITLE
请求添加mts扩展名支持

### ISSUE THREAD

**Issue by xianfei** [xupefei/QuickLook#167]
（作为一个经常剪视频的人这个插件真的是太棒！）
能否添加mts为扩展名的avchd h264视频格式的支持，我直接把扩展名mts改成mp4然后按空格键可以预览的！

**Comment by xupefei** [comment]
![image](https://user-images.githubusercontent.com/1687847/35284042-7d284c12-0062-11e8-8b87-816ea435bbfa.png)
代码里已经有了呀。你确定是mts？

**Comment by xianfei** [comment]
![image](https://user-images.githubusercontent.com/8101613/35328428-437dbe2c-0137-11e8-8812-641d6118e90e.png)
是mts啊  Sony摄像机录得

**Comment by xupefei** [comment]
很奇怪，我找了个mts试了试，可以播放。
你把这个文件复制到全英文目录里再试试？或者你把后缀改成m2ts再试试？

**Comment by xianfei** [comment]
![image](https://user-images.githubusercontent.com/8101613/35341438-b02137f6-0160-11e8-9084-f218148a3826.png)
改成m2ts和mp4都能播放 但是mts不行  我的笔记本和台式机都不行（分别是win10 1703和1709） 复制的c盘根目录测试的

**Comment by xupefei** [comment]
奇怪。试一试最新的nightly版？

**Comment by xianfei** [comment]
![image](https://user-images.githubusercontent.com/8101613/35342536-4b4b54d0-0163-11e8-851b-a8ed30fe1316.png)
最新的nightly版是可以的  非常感谢  （如果能加入隔行反交错就更好了  学校的老dv都是50i的帧率）
（话说nightly版的透明背景超好看）
