### ISSUE TITLE
Command line problem

### ISSUE THREAD

**Issue by liulex** [xupefei/QuickLook#17]
Version: 0.1.9
By executing`/path/to/QuickLook.exe /path/to/some/file`, the preview window shows up as expected.

When I execute the same command again, according to the usage, the preview window should close itself, but what I get is:
![snipaste_20170521_120910.png](https://cloud.githubusercontent.com/assets/2010459/26281075/3e79125a-3e1e-11e7-8ab7-d555be85940c.png)

**Comment by xupefei** [comment]
This issue has already be fixed in 44187f845a297658a4f5e20919fa54a5f353f1c8. You may expect the next release.
