### ISSUE TITLE
Problems with CSV preview

### ISSUE THREAD

**Issue by ZhangTianrong** [xupefei/QuickLook#170]
QuickLook works nicely when there's no multi-column cells, but if there do exist such cells, only the first column will be displayed in the preview. Screenshots helping to illustrate are as follow:
![001](https://user-images.githubusercontent.com/20651728/35376697-2cc076c4-01e7-11e8-9c10-d2881504953d.png)
![002](https://user-images.githubusercontent.com/20651728/35376705-30a4a40e-01e7-11e8-8a1d-14c596a7f5fd.png)
![003](https://user-images.githubusercontent.com/20651728/35376762-73dbc072-01e7-11e8-90ea-0df14796b694.png)

**Comment by xupefei** [comment]
It seems that your CSV file is not valid. A valid CSV must have all lines with the same number of columns (separated by , or ;) [REF <https://en.wikipedia.org/wiki/Comma-separated_values#Specification>], whereas in your file the first line contains only one column.

A fix for your file can be:
Line 1: Device data for … 08/2016,,
Line 2: Site ID,Time,INC_MD
Line ...: ...

cheers,
Paddy

**Comment by Vijay-Nirmal** [comment]
CSV file works properly for me

![2018-01-26_16-57-25](https://user-images.githubusercontent.com/24755596/35437832-2c0bd308-02ba-11e8-9fbf-cefc65c9a928.png)

@xupefei If I delete the names from columns after the first column, still works.

![2018-01-26_17-02-41](https://user-images.githubusercontent.com/24755596/35437985-c710964a-02ba-11e8-870d-8efdf3f5a58b.png)

**Comment by xupefei** [comment]
@Vijay-Nirmal It because when you delete it using Excel, it still has commas left.
Try you delete the commas using Notepad :)

**Comment by Vijay-Nirmal** [comment]
Ya, @xupefei you are right

![2018-01-26_17-08-49](https://user-images.githubusercontent.com/24755596/35438220-aae4a2ee-02bb-11e8-9180-77fbaa6aba56.png)

**Comment by ZhangTianrong** [comment]
@xupefei Thank you for telling me the standardization of CSV files, but since generally people process or view them in Excel, I think it better if Quicklook displays in a similar way.

**Comment by xupefei** [comment]
Even Excel can save CSV correctly (as previous comments mentioned) because it adds "," to empty columns.

I think your problem is the producer of such CSV file. If you are not able to modify it, I would suggest you remove the plugin `QuickLook.Plugin\QuickLook.Plugin.CsvViewer`, therefore the file can be previewed as pure text.
