### ISSUE TITLE
Icon suggestion

### ISSUE THREAD

**Issue by Vijay-Nirmal** [xupefei/QuickLook#173]
Don't use 'share icon' for 'open with'. Use E7AC or E8E5

![chrome_2018-01-27_20-09-50](https://user-images.githubusercontent.com/24755596/35472920-21b7846c-039e-11e8-8a7b-c88c42cc1806.png)

![chrome_2018-01-27_20-10-18](https://user-images.githubusercontent.com/24755596/35472924-2596a0b8-039e-11e8-9559-a7deaa6fe5c2.png)

Also, provide tooltip for every button

**Comment by Vijay-Nirmal** [comment]
@xupefei What about tooltips?

**Comment by xupefei** [comment]
They are being added a few days ago.
