### ISSUE TITLE
Windows Timer Resolution Issue

### ISSUE THREAD

**Issue by AliveDevil** [xupefei/QuickLook#178]
I just noticed that the moment I start up QuickLook it immediatly sets the Windows Timer Resolution from 15,6ms to 1ms which should not occur. Is there any reason why this is done? Would like to see a fix for this.

https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/

**Comment by xupefei** [comment]
Thanks for the reporting.
I have fixed this issue in commit a97a01f5ba3d68cd45f520e6da64a93a8734d94a. Try the latest Nightly version!
