### ISSUE TITLE
Touchscreen support: Dragging on touch screen highlights instead of scrolling

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [xupefei/QuickLook#18]
When I preview a large plain text file with QuickView, then dragging on touch screen, the texts are simply selected as a traditional mouse drag, not being draagged.

**Comment by xupefei** [comment]
I still havn't got enough time for adapting touchscreen. But it is a must-do.

**Comment by xupefei** [comment]
Solved in b0e8a29f856cf6b9d3c8da52754240e7875b64e3.
