### ISSUE TITLE
WAV files

### ISSUE THREAD

**Issue by fantasiom** [xupefei/QuickLook#180]
I noticed that WAV audio files were not working.  The window pops up and acts like it's playing but not audio is heard.  mp3 and smaller compressed formats work perfectlyl.  Are WAV files supported?

**Comment by xupefei** [comment]
I tested with the latest version and it works.
Which version are you using?

**Comment by fantasiom** [comment]
Thanks for you response!  version 0.3.2.1

**Comment by xupefei** [comment]
How about [this](https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts)?

**Comment by fantasiom** [comment]
that's it!  It works!  Thank You!
