### ISSUE TITLE
Cannot preview .doc/.xls/.ppt

### ISSUE THREAD

**Issue by LaaaCroqueta** [xupefei/QuickLook#185]
The whole Microsoft Office has been installed, but when I want to preview those files, Quick look doesn't work. I wonder what may cause the problem and how to solve it. Thanks a lot!
![image](https://user-images.githubusercontent.com/36318617/36057731-4a900332-0e4d-11e8-8140-39b2811fb87b.png)

**Comment by xupefei** [comment]
Can you preview it in File Explorer's preview pane?

(I haven't installed Office on this PC thus it shows "No preview available")
![image](https://user-images.githubusercontent.com/1687847/36059990-5f047d16-0e48-11e8-91f9-debe5a9eb904.png)

**Comment by xupefei** [comment]
That's true. Microsoft stats that the Office in Windows Store does not provide COM support which is necessary for previewing.
