### ISSUE TITLE
QuickLook is not focused when opening with F3 in Total Commander

### ISSUE THREAD

**Issue by mmqmzk** [xupefei/QuickLook#192]
QuickLook version 0.3.4
Total Commander version 9.12
It was good when I use version 0.3.2.1

**Comment by xupefei** [comment]
It is designed works like this. Press F3 again will close the preview.

**Comment by mmqmzk** [comment]
Thanks for reply, I get it.

**Comment by mmqmzk** [comment]
But I can not close QuickLook window by press F3 again.
It was good when I use version 0.3.2.1.

**Comment by mmqmzk** [comment]
Version 0.3.3 has the same problem.
I roll back to 0.3.2.1 and it works well again.

**Comment by xupefei** [comment]
Oops,  my fault.
