### ISSUE TITLE
Issue with audio files theme scheme

### ISSUE THREAD

**Issue by ArianMozafari** [xupefei/QuickLook#194]
First of all, thanks for providing this wonderful software!
There's an issue with previewing audio files which text and window controls turn white or stay black (default) and window background adapts a blurred version of the artwork, however sometimes (specially with dark artworks) text stay black while background is dark as well which makes text harder to read. I suggest keeping preview always with the light theme, if the audio file has an artwork background still adapts it but with a lighter shade and text (and controls) always stay dark. 
![capture](https://user-images.githubusercontent.com/11410707/36715576-fd4288e0-1bab-11e8-9cfd-d9420734102f.PNG)

**Comment by xupefei** [comment]
It's quite hard to tell whether an image is "dark" or "light".

Maybe it's better to apply a grey filter above the background.

**Comment by Darthagnon** [comment]
Maybe text glow? I remember in Windows 7, all Explorer windows actually had black text only, with this sort of glow behind it to make it legible, despite Aero transparencies.
