### ISSUE TITLE
Music artwork is deleted from music folders when previewing music files

### ISSUE THREAD

**Issue by adrianghc** [xupefei/QuickLook#195]
Windows Media Player automatically creates a file called Folder.jpg inside a music library folder containing the folder's album art, or a file called AlbumArtSmall.jpg or AlbumArtLarge.jpg. QuickLook pulls one of these if it can to display the album art of a previewed music file in that folder, apparently the one with the largest resolution it can find (usually Folder.jpg). However, this file is always automatically deleted by QuickLook when closing the preview of a music file in that folder. This applies to the Microsoft Store version and the ZIP standalone version, possibly the MSI version as well.

**Comment by xupefei** [comment]
Cool. I never thought there will be this case.

**Comment by adrianghc** [comment]
Does this mean you know what the cause is?

**Comment by xupefei** [comment]
Yes :)

**Comment by adrianghc** [comment]
Great news, so does this mean a fix can be expected soon as well?

**Comment by xupefei** [comment]
You may have to wait for the next Store version to get this fixed, or just try the Nightly version :)

**Comment by adrianghc** [comment]
Obviously a fix would require a new version, just wanted to know if you already knew a fix you could implement quickly. ^^ Looking forward to it. I just discovered your app today via Reddit and so far I really like it, keep up the great work! :)

**Comment by xupefei** [comment]
Look back in this issue. It has been fixed now 😜

**Comment by adrianghc** [comment]
Fantastic, thank you very much for reacting so quickly! :)
