### ISSUE TITLE
预览后缀名为tp或ts格式的1080p视频时预览窗口太小

### ISSUE THREAD

**Issue by dearanswer** [xupefei/QuickLook#197]
预览同样是1080p分辨率格式为mp4格式的视频时窗口大小就为720p很舒适

**Comment by xupefei** [comment]
可能是获取尺寸信息失败了。能否给个小点儿的文件测试一下？

**Comment by dearanswer** [comment]
链接: https://pan.baidu.com/s/1vL7l_yI-F74PxBIz85w08w 密码: hd9i

**Comment by RichieChow** [comment]
BDMV的m2ts存在同样的问题，跳转会有短暂绿屏，跳转时硬解占用反而低了
链接：https://pan.baidu.com/s/1KMBmMwsDzId0U7MjU8-1CQ 密码：nrnk
