### ISSUE TITLE
[Suggestion] Enable the key Escape to close the preview

### ISSUE THREAD

**Issue by gigios** [xupefei/QuickLook#2]
Is it possible to adde the management of a key to close the preview?
Of my point of view it's very unconfortable to close the preview window by pressing the 'x' button to close the window.

**Comment by gigios** [comment]
Sorry, I have found now that by pressing a second time the 'space' key the preview will be closed.

**Comment by xupefei** [comment]
The ESC key will enter into effective in the upcoming updates.

**Comment by kintrupf** [comment]
The post above suggests that closing the QuickLook window with ESC should work.
But it does not seem so, pressing ESC does nothing, only SPACE closes the window.
