### ISSUE TITLE
Don't work in PC x64: vc_redist not installed

### ISSUE THREAD

**Issue by noulox** [xupefei/QuickLook#20]
![2017_05_26_10_15_52_](https://cloud.githubusercontent.com/assets/28976401/26486752/c914cda0-41fc-11e7-8f39-d3b88ee4200e.jpg)

**Comment by xupefei** [comment]
Sorry I can't read Spanish. Could you translate it to English?

**Comment by noulox** [comment]
Unable to load DLL ... The specified module can not be found
Thank you for your attention.

**Comment by xupefei** [comment]
Does the file exists next to the QuickLook.exe? If yes, do you have any antivirus software blocking it?

**Comment by noulox** [comment]
The file exists next to the .exe, I stopped the antivirus but it still does not work...

**Comment by xupefei** [comment]
Can you try installing the "Microsoft Visual C++ Redistributable for Visual Studio 2017" ("vc_redist.x86.exe") from https://go.microsoft.com/fwlink/?LinkId=746571?

**Comment by noulox** [comment]
Solved, It's work!!
Thank you very much!!

**Comment by xupefei** [comment]
Thanks for the feedback. I will include this in the next release :)
