### ISSUE TITLE
预览GIF图片时加载速度较慢

### ISSUE THREAD

**Issue by Leolion610** [xupefei/QuickLook#207]
1. 预览GIF图片时加载速度较慢，稍大的文件会有很明显的延时。内存占用高达1.3GB。建议参考这个项目进行性能优化：https://github.com/XamlAnimatedGif/XamlAnimatedGif ，预览同样的GIF图片，内存占用40MB左右。版本：v0.3.5。
2. 退出预览后，进程仍然有近100MB的内存占用，有优化空间。
3. 好工具，感谢作者的付出！

**Comment by xupefei** [comment]
很久以前 QuickLook 也是用 XamlAnimatedGif 的。然而这个库的异步解码有严重的内存泄漏，后来我写了个同步解码器凑合用到了今天。这就是为什么预览多帧GIF是这么慢。

至于关闭后 100MB 的内存占用，这个是 CLR 的缓存，空闲一段时间／预览其他文件后被会被逐渐释放掉。不存在内存泄漏。

**Comment by Leolion610** [comment]
> 很久以前 QuickLook 也是用 XamlAnimatedGif 的。然而这个库的异步解码有严重的内存泄漏，后来我写了个同步解码器凑合用到了今天。这就是为什么预览多帧GIF是这么慢。

我做了一个小测试，定时切换 GIF 源，长时间运行观察内存变化。XamlAnimatedGif 库内存占用始终在40~50MB（WpfAnimatedGif 库内存占用有时会高达 2GB），未发现内存泄漏 。我觉得可以重新对 XamlAnimatedGif 库进行评估，我经常会预览超过 1MB 的 GIF 图片，XamlAnimatedGif 方案从体验上来说比现有的要好一些，现在预览需要等待几秒才能显示。

> 至于关闭后 100MB 的内存占用，这个是 CLR 的缓存，空闲一段时间／预览其他文件后被会被逐渐释放掉。不存在内存泄漏。

你说得对，内存过一段时间会释放掉。

**Comment by guobing1993** [comment]
遇到同样的问题，希望作者优化，感谢作者付出！

**Comment by xupefei** [comment]
Fixed in db31458ffef48396770599eefc20214675e9fbdb.
