### ISSUE TITLE
I can't use the portable version

### ISSUE THREAD

**Issue by skyoflovehc** [xupefei/QuickLook#21]
When I am  using it, an error window popup:
![snipaste_20170526_194100](https://cloud.githubusercontent.com/assets/16860505/26493363/afadc57a-424b-11e7-82f1-cd42050a7922.png)

**Comment by xupefei** [comment]
Can you install the Visual C++ Redistributable as in #20 and try again?

**Comment by skyoflovehc** [comment]
I installed  the Visual C++ Redistributable for VS 2017(x86 and x64 ),but it still doesn't work.

**Comment by xupefei** [comment]
How about the `.msi` package? Does it works?

**Comment by skyoflovehc** [comment]
I install the .msi, but  still doesn't work.I want to give up.hahaha

**Comment by xupefei** [comment]
Something might not right in your PC. Anyway, thanks for reporting and good luck :)
