### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by Kenya-West** [xupefei/QuickLook#215]
Since it's Centennial Bridge app, it can recognize which theme is currently on in Windows. If it's dark theme, can it have dark style?

**Comment by xupefei** [comment]
QuickLook is not only Centennial Bridged, but also distributed via msi installer and portable package. Moreover, it also needs to consider Windows 7 users who do not have a global dark theme in Windows.

I still need to figure out the best practice to enable the dark theme of QL.

**Comment by xupefei** [comment]
It's done!
If your Windows 10 is using a dark theme, QL will do it too.

**Comment by Silvery-Corgan** [comment]
This is still an issue in 0.3.5

Why not make a settings panel? Or something where we can set the dark theme manually?

**Comment by xupefei** [comment]
This feature is now only in the Nightly version. Version 0.3.5 does not respond to light/dark theme.

Cheers,
Paddy
