### ISSUE TITLE
Script in HTML crashes QuickLook

### ISSUE THREAD

**Issue by Milly** [xupefei/QuickLook#22]
Viewing `crash.html` and ...
* The Viewer can not be closed with the close (`X`) button. (can close with space key.)
* After that, can not view all HTML files. (by alert dialog.)
* `CefSharp.BrowserSubprocess` may crash some case.
* `QuickLook.exe` may crash some case.

## crash.thml
```html
<html>
<script>
for(;;) alert(1);
</script>
</html>
```

**Comment by xupefei** [comment]
I have disabled all dialogs invoked by javascript. Now this html will not locks the preview panel.
