### ISSUE TITLE
can support listary?

### ISSUE THREAD

**Issue by lmovse** [xupefei/QuickLook#230]
it's a wonderful app, Thank you very much! But unfortunately it does not support **Listary**, i had seen the support list have **Everything**, I think these two softwares belong to similar file manager software,so, can `quickLook` support **Listary**? hope your answer, thanks!

**Comment by xupefei** [comment]
I am confused. What do you mean by "support"? Do you want to preview selected file in Listary with QL?

**Comment by lmovse** [comment]
yes, as you said

**Comment by xupefei** [comment]
Then you should add a custom command in Listary:
![http://i1-win.softpedia-static.com/screenshots/Listary_22.png](http://i1-win.softpedia-static.com/screenshots/Listary_22.png)

You can find QL's command line here: https://github.com/xupefei/QuickLook/wiki/Integration-and-Development

**Comment by lmovse** [comment]
Understand,thank you,I'll close this issue
