### ISSUE TITLE
WinQuickLook

### ISSUE THREAD

**Issue by Semidio** [xupefei/QuickLook#234]
https://www.microsoft.com/store/productId/9NJMTKK6JC0Q

这个和QuickLook是什么关系。

**Comment by xupefei** [comment]
没什么关系。

<img width="927" alt="screen shot 2018-05-10 at 14 45 13" src="https://user-images.githubusercontent.com/1687847/39868102-c666c8e8-5460-11e8-8557-92a429d82ad7.png">
