### ISSUE TITLE
MSI version doesn't delete files when uninstalled

### ISSUE THREAD

**Issue by Darthagnon** [xupefei/QuickLook#235]
I uninstalled the MSI version of Quicklook from my current old computer (since it's a bit underpowered for plugins - I'll definitely be using Quicklook on my new computer). I had installed Quicklook to C:/Program Files, and when I uninstalled it from the Control Panel, it left the Quicklook folder behind with the executable, Quicklook files, etc.

**Comment by xupefei** [comment]
QL does not acquire admin right, so it can't delete any file under C:\Program Files folder. Is not advised to install QL into this folder. Stick with the default path (AppData\Local) instead
