### ISSUE TITLE
希望增加EXIF图标可见性

### ISSUE THREAD

**Issue by RichieChow** [xupefei/QuickLook#236]
某些图片右上角EXIF图标会极难辨识
![snipaste_2018-05-14_17-08-25](https://user-images.githubusercontent.com/34783557/39988471-fe43bfdc-5799-11e8-8a6b-3bf59625aa50.png)

**Comment by xupefei** [comment]
The icon will be merged into https://github.com/xupefei/QuickLook/pull/183 in the future.
