### ISSUE TITLE
不支持rar 5.x文件

### ISSUE THREAD

**Issue by ZzMark** [xupefei/QuickLook#237]
无法预览rar文件，按下空格后一直在Loading archive...

压缩用 winrar 5.50，压缩格式选择RAR不是RAR4，其他不变
工具版本 UWP v0.3.5

顺便请求下，直接预览html代码的功能，硬盘里的html文件大部分都不是为了看效果而是当作文本文件看的吧，希望有个按钮能切过来

**Comment by xupefei** [comment]
Fixed in upstream SharpCompress and d4feb2c86798e2bd53d374461289923ade3b8d6f.
