### ISSUE TITLE
word、excel、ppt文件均无法预览

### ISSUE THREAD

**Issue by Cheney1997** [xupefei/QuickLook#239]
系统为win10专业版，正版微软商店里安装的office2016，word、excel、ppt均只显示文件名字和图标，不能预览内容。

**Comment by xupefei** [comment]
商店版 Office 不支持COM组件，所以无法用来显示预览。
这一点在微软的网站上提到过。

Cheers,
Paddy

From: Cheney1997
Sent: 17 May 2018 19:09
To: xupefei/QuickLook
Cc: Subscribed
Subject: [xupefei/QuickLook] word、excel、ppt文件均无法预览 (#239)

系统为win10专业版，正版微软商店里安装的office2016，word、excel、ppt均只显示文件名字和图标，不能预览内容。
