### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by CyshallChan** [xupefei/QuickLook#244]
首先感谢作者，非常Nice的软件。
其次，作者有考虑过增加夜间模式么？

**Comment by xupefei** [comment]
最新的nightly版已经有了。配色跟随win10系统设置。

**Comment by CyshallChan** [comment]
![quicklook](https://user-images.githubusercontent.com/22564041/40306273-a1bc7582-5d30-11e8-9179-989ece676b7e.png)
刚试了下Nightly版本，发现夜间模式仅仅只是边框- - 。 我的意思是预览文字文件时（比如代码文件 ）的底色也可以是黑色这种。

**Comment by xupefei** [comment]
文本查看器没有夜间模式。没人写夜间的代码高亮方案。

cheers,
Paddy

**Comment by CyshallChan** [comment]
OK，了解了，感谢回答！
