### ISSUE TITLE
似乎与windows资源管理器插件clover有冲突

### ISSUE THREAD

**Issue by lurui45** [xupefei/QuickLook#246]
win7平台，桌面可以正常使用，但是资源管理器里面，按空格键是没有反应的，我安装了clover这款资源管理器增强软件，就是是资源管理器和浏览器一样带标签。
win10平台下，同样安装了clover，但是按空格的话，相当于在右上角的搜索栏里面敲了一个空格键。

**Comment by xupefei** [comment]
Duplicate of https://github.com/xupefei/QuickLook/issues/107 and https://github.com/xupefei/QuickLook/issues/213.
