### ISSUE TITLE
PDF Display Default Suggestion - No Thumbnails, Text Width

### ISSUE THREAD

**Issue by ghost** [xupefei/QuickLook#248]
**Is your feature request related to a problem? Please describe.**
When running QuickLook on a PDF, its default is with page thumbnails displayed and view-entire-page.  This is not an optimal viewing condition for getting a "quick look" at the file's contents, since a full page view makes the PDF's content illegibly small, as does the decreased width offered when thumbnails are enabled.

**Describe the solution you'd like**
I would suggest that the PDF default display setting be 'view width' (i.e. fit the PDF's width to the window width) with thumbnails disabled.

**Describe alternatives you've considered**
None.

**Additional context**
None.
![untitled](https://user-images.githubusercontent.com/39887155/40891146-5f2b10dc-6746-11e8-9547-595ab1035479.png)

**Comment by xupefei** [comment]
Sorry, but I will not do this. Changing viewing options require a huge amount of work, but its benefit is not much significant. As the baseline, QL is designed for quickly finds the file you want, you should read contents with another application.

BTW, I will happy to merge the changes if somebody is willing to do it :)
