### ISSUE TITLE
Can't preview PDF file

### ISSUE THREAD

**Issue by nBlueDev** [xupefei/QuickLook#249]
**Describe the bug**
I simply can't preview PDF file contents. It just makes a preview of PDF info (Thumbnail, file name, date modified and size in KB). 

I just want to mention that this was working sometimes in previous versions, but I didn't like how it worked. I didn't like it's behavior when the file is huge (like 30MB) and it freezes for some amount of time while loading. I just think that a better approach should be that there is a some kind of loading animation (or just a simple text) while processing the file and that I can close the preview if it takes too much time to open. It is really annoying when it freezes while processing the file and I can't close (quit) until it is done processing.

**To Reproduce**
I select a file and then I press space to view it.

**Expected behavior**
It should make a contents preview screen like it does normally...

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro - 1803
 - QuickLook Version: v0.3.5-22-g10b2c4b downloaded from AppVeyor

**Screenshots and Exception Log**
[QuickLook.Exception.log](https://github.com/xupefei/QuickLook/files/2068286/QuickLook.Exception.log)
Image (Contents not showed)
![Image (Contents not showed)](https://user-images.githubusercontent.com/8507831/40918776-9e5d6dba-6807-11e8-822f-182108c30869.jpg)

I know that this is a nightly build, but those major features should always work. However, your software is currently the best one we can find for this purpose (for free). It doesn't have any options to configure, like alternatives, but it always works as desired. These little things can be fixed easily in order to put QuickLook on the solid first position.

Keep a good work and thank you for sharing such as amazing piece of software! ;)

**Comment by xupefei** [comment]
Are you
* Using an English OS and
* The PDF's name contains Cyrillic alphabets?

**Comment by nBlueDev** [comment]
Yes, i use English OS. The document I tried to open (from image above) does not contain any Cyrillics, but it does contain letters from Croatian/Bosnian/Serbian latin (Č Ć Ž Š Đ).

**Comment by xupefei** [comment]
Sorry for saying “Cyrillic”... European language always looks like Cyrillic to me😅

This issue is caused by the “Č Ć Ž Š Đ”’s in the file name because PDFium does not handle non-ASCII characters.

I will fix it soon.

Cheers,
Paddy

**Comment by nBlueDev** [comment]
I can understand how you see these weird letters together... 😂😂😂 

Thanks for your answer and I hope you will take a look at the problem I mentioned which is related to "freezing while processing" issue, and that you will use my suggestion...

Thanks again! 😉
