### ISSUE TITLE
QuickLooking a PDF file with Hebrew characters in its name causes error

### ISSUE THREAD

**Issue by YanovskyOr** [xupefei/QuickLook#257]
**Bug Description**

When pressing space while a PDF file with Hebrew characters in its name selected, an error message appears.

**To Reproduce**

1. Select a PDF file with Hebrew characters in its name
2. Press 'Space' key
3. Error pops up

**Expected behavior**

Normal QuickLook preview of the PDF file

**Desktop (please complete the following information):**

 - OS Version: Windows 10 1803
 - QuickLook Version: 0.3.5 from Windows Store

**Screenshots and Exception Log**

![image](https://user-images.githubusercontent.com/21991428/41675076-5ee963c6-74ca-11e8-8913-2147d2cb72a4.png)

========20/6/2018 8:36:51 PM========
PDFiumSharp.PDFiumException: PDFium Error: File not found or could not be opened.
   at PDFiumSharp.Types.NativeWrapper`1..ctor(T handle)
   at PDFiumSharp.PdfDocument..ctor(FPDF_DOCUMENT doc)
   at QuickLook.Plugin.PDFViewer.PdfViewerControl.GetDesiredControlSizeByFirstPage(String path)
   at QuickLook.Plugin.PDFViewer.Plugin.Prepare(String path, ContextObject context)
   at QuickLook.ViewerWindow.BeginShow(IViewer matchedPlugin, String path, Action`2 exceptionHandler)

**Comment by xupefei** [comment]
This issue has been fixed in https://github.com/xupefei/QuickLook/issues/249 <https://github.com/xupefei/QuickLook/issues/249>.

Have a try at the Nightly build :)

Cheers,
Paddy

**Comment by YanovskyOr** [comment]
It works! Thanks for the quick response!
How long until Win Store update? 😁

**Comment by xupefei** [comment]
No TBA yet. Still lots of issues to fix.

Cheers,
Paddy
