### ISSUE TITLE
The file preview does not open if user hits SPACEBAR within the file selection dialog when uploading files.

### ISSUE THREAD

**Issue by cstamatis** [xupefei/QuickLook#259]
**Description**
The file preview does not open if user hits the SPACEBAR button within the file selection dialog when uploading files.

**To Reproduce**
1. Open your browser of choice
2. Navigate to https://uploadfiles.io/
3. Click to upload files
4. On the file selection dialog, highlight any file/folder
5. Press SPACEBAR

**Expected behavior**
The file preview should open

**Desktop:**
 - Windows 10 1803
 - QuickLook 0.3.5 from Windows Store

**Comment by xupefei** [comment]
It's documented here:
https://github.com/xupefei/QuickLook/wiki/Difference-between-distributions
