### ISSUE TITLE
Support APNG

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [xupefei/QuickLook#26]
QuickLook should making APNG image animatable while loading it.

**Comment by xupefei** [comment]
This is quite a lot of work since there is no existing rendering solution for APNG on WPF.

**Comment by charlesmilette** [comment]
There is, actually!
https://github.com/Bungalow12/AnimatedImage

**Comment by xupefei** [comment]
That control is for Winform, not WPF.
My idea is to use FFmpeg to decode the APNG file, similar to a video file (I will also decode GIF file with it). I am currently waiting for the beta release of https://github.com/unosquare/ffmediaelement and then give a try.
