### ISSUE TITLE
Photo preview zoomed in

### ISSUE THREAD

**Issue by gaymer313** [xupefei/QuickLook#261]
When you preview a photo, it's zoomed way in all the way.

**Describe the bug**
When you preview a photo, it's zoomed way in all the way

**To Reproduce**
1. Go to the file
2. Hit spacebar

**Expected behavior**
To view the photo the whole photo.

**Desktop (please complete the following information):**
 - OS Version: Version	10.0.17134 Build 17134
 - QuickLook Version: 0.3.5.0 Windows Store

**Screenshots and Exception Log**

![screen](https://user-images.githubusercontent.com/40505674/41802382-563b9caa-764e-11e8-9626-6420b451ee81.png)

**Comment by xupefei** [comment]
Could you share this file?

**Comment by gaymer313** [comment]
Sure, here is the file.
![20180615_163659](https://user-images.githubusercontent.com/40505674/41859074-5c5c628c-7869-11e8-91f3-60e79ceaba6b.jpg)

**Comment by xupefei** [comment]
The latest Nightly should have this issue fixed :)
