### ISSUE TITLE
Display problem with Word and Excel on Surface Pro

### ISSUE THREAD

**Issue by achan2ix** [xupefei/QuickLook#269]
I have Quick Look on a Compute stick and a Surface Pro 3 running Windows 10. On Compute stick everything works fine, on Surface Pro 3 PDF, PPT, and image files work fine. Word and Excel files do not display correctly. I have attached the actual files and screen capture. As you can see a small portion of the text is displayed correctly.

If there are information that you need me to look up please let me know.

Thanks,
Andrew

[RFID_tracking_methods.docx](https://github.com/xupefei/QuickLook/files/2131117/RFID_tracking_methods.docx)
[Holiday.xlsx](https://github.com/xupefei/QuickLook/files/2131118/Holiday.xlsx)
![holiday_xls_capture](https://user-images.githubusercontent.com/40546632/41822595-cd1a2f8e-77b7-11e8-97da-38dfa8af7dc6.jpg)
![rfid_docs_capture](https://user-images.githubusercontent.com/40546632/41822596-cd281054-77b7-11e8-8ad5-b29c76620ab5.jpg)

**Comment by xupefei** [comment]
This is a problem of Office. Please update to a newer Office suite, like 2016.
