### ISSUE TITLE
建议窗口失去焦点时自动关闭

### ISSUE THREAD

**Issue by S7venYoung** [xupefei/QuickLook#27]
有时候可能按下空格键，手快就直接点击了其他窗口，可否考虑当预览窗口失去焦点时，自动关闭呢 # @

**Comment by xupefei** [comment]
不，这个不会考虑。如果你把预览放旁边在记事本里打字，这时预览自动关闭的话就太不好了。
失去焦点时不关闭这也是水果系统目前的做法。

**Comment by S7venYoung** [comment]
好吧，貌似macOS也是不自动关闭，还真没注意到

**Comment by ivysrono** [comment]
那能否不强制前台呢？
