### ISSUE TITLE
Possible bug with QuickLook.WoW64HookHelper.exe

### ISSUE THREAD

**Issue by Theoremly** [xupefei/QuickLook#279]
Some days ago I want to start the Android Studio debug mode to test an app, but it failed. I went to the Task Manager and find the QuickLook.WoW64HookHelper.exe was running in the background. The I killed the process and the Android Studio debugger returned to normal.
<br/>
<br/>
Environment:
<br/>
Android Studio Version: 3.1.3
<br/>
Windows Version: Windows 10 Pro 1803

**Comment by xupefei** [comment]
Have you performed multiple COST (Changing One Single variable at a Time) experiments? Do Android Studio behaviour the same across all experiments?

**Comment by Theoremly** [comment]
Sorry, I was busy at that time and I didn't perform the multiple COST. I have performed some tests these days, and this problem didn't appear again. I apologize for my carelessness.
