### ISSUE TITLE
建议不支持的格式能否选择默认以文本方式查看

### ISSUE THREAD

**Issue by xkonglong** [xupefei/QuickLook#28]
比如很多文本格式的文件, 比如 .ini  .config   .nsis   等等.    未必一定要关联到每个格式.  但可以选择以文本方式查看.

**Comment by xupefei** [comment]
现在不就是以文本显示吗？

**Comment by xkonglong** [comment]
昨天还不行,只能显示文件信息, 今天就可以了.奇怪.
