### ISSUE TITLE
Feature Request: Allow Previewing of File Linked with file shortcut

### ISSUE THREAD

**Issue by sahil48** [xupefei/QuickLook#284]
**Is your feature request related to a problem? Please describe.**
I select a shortcut. I see a small thumbnail of the file.

**Describe the solution you'd like**
I would like to be able to preview the actual file straight from the preview of the thumbnail from Quickbooks.

**Comment by xupefei** [comment]
Fixed in https://github.com/xupefei/QuickLook/issues/120.
