### ISSUE TITLE
Add quicklook feature for "browse" windows

### ISSUE THREAD

**Issue by volcbs** [xupefei/QuickLook#287]
In MacOS, you can use the quick look in "browse" windows. It's actually really useful (at least for me) to use the quicklook, since you can make sure you upload/choose the right file.
So I hope you can add this program to "browse" windows.

Thanks.

**Comment by xupefei** [comment]
The msi or portable package can do that: https://github.com/xupefei/QuickLook/wiki/Difference-between-distributions
