### ISSUE TITLE
开启桌面整理软件，无法预览桌面上的文件

### ISSUE THREAD

**Issue by MrYangyt** [xupefei/QuickLook#289]
win10.1803开启360桌面整理软件就无法预览桌面文件了，测试了一下腾讯桌面整理软件也是开启后无法预览，不知道是此软件的问题还是桌面整理软件的问题。往可以检查解决下，谢谢。

**Comment by xupefei** [comment]
QL不兼容360和腾讯的桌面整理软件。请使用[Fences](https://www.stardock.com/products/fences/)。

**Comment by guxuanjun** [comment]
事实上使用Fences只能预览放在桌面上的文件。
不知道能否实现预览Fences的文件夹快捷入口中的文件？

**Comment by JiadongZhang** [comment]
fences 3有**桌面页面**和**文件夹快捷入口**两个功能。
QuickLook能够在**桌面页面**使用。
QuickLook无法在**文件夹快捷入口**上使用。
当我在桌面上建立一个快捷入口去链接我的**下载文件夹**，在这个情境下，QuickLook无法工作。

**Comment by xupefei** [comment]
@JiadongZhang 你可能要联系Fences开发商，让他们支持QuickLook :)

**Comment by fr1g** [comment]
> @JiadongZhang 你可能要联系Fences开发商，让他们支持QuickLook :)

比较好奇为什么QL方面无法支持，是因为fences没有对外暴露选中文件的路径吗

**Comment by 1212a** [comment]
找到.exe程序，右击属性设置以管理身份运行就可以了
