### ISSUE TITLE
能否支持其他软件,比如everything

### ISSUE THREAD

**Issue by xkonglong** [xupefei/QuickLook#29]
everything虽然自带预览,但是不好用. 
其他比如Qdir,Tc 能不能也支持.  

简单说就是在其他软件里,也可以通过按下空格来预览.

**Comment by xupefei** [comment]
https://github.com/xupefei/QuickLook#usages

**Comment by xkonglong** [comment]
这个方法对其他软件要求比较高,比如不支持自定义快捷键等等.
 算了,我自己写个ahk脚本吧.

**Comment by xupefei** [comment]
ahk 能拿到各种第三方文件管理器内选中文件的具体路径？

**Comment by xkonglong** [comment]
```
F4::
	send ^c
	sleep,200
	clipboard=%clipboard%   ;转换路径为字符串.其实多数情况下不用这句代码
	RunWait D:\QuickLook\QuickLook.exe %Clipboard%
Return

```

但是,有个问题, 不关闭quicklook的情况下, 再执行一次,quicklook是没有反应的

**Comment by xkonglong** [comment]
所以我觉得quicklook 是否也可以用类似方法内置该功能. 

通过复制的方式,获取文件路径.  这样的话, 多数支持复制文件的软件, 都可以使用ql.

**Comment by xupefei** [comment]
这样岂不是很容易误操作…而且擅自修改剪切板内容也不好。

**Comment by ivysrono** [comment]
对我等 TC/DC/Everything/Listary 党人来说，这种工具想用又基本没用。

**Comment by xupefei** [comment]
TC F3 预览内置的查看器还是算了吧，看个文本还凑合。Listary 能预览？
我自己给Listary设了个快捷键指定给 QuickLook，还挺好用。

**Comment by ivysrono** [comment]
就是因为 TC/DC 的内置查看器太烂，LIstary 不支持，才想要找好用的啊。

**Comment by xupefei** [comment]
那为啥会 “这种工具想用又基本没用”？那些文件管理器都能自己指定预览工具啊。

**Comment by ivysrono** [comment]
因为用Seer的时候作者说没办法……

**Comment by xupefei** [comment]
对于这个 issue 里说到的Everything的确没办法，因为它不支持自定义快捷键（上面的复制路径法是曲线救国）。这个是 Everything 那边的问题。
但是 TC 和 Listary 都可以指定查看器，比如 TC 选项里就有个自定义 F3 的查看器；Listary 可以添加一个自定义动作。命令行写 `QuickLook.exe path-here` 就能用了。

**Comment by xupefei** [comment]
我正在想要不要把空格键也搞成插件，这样就可以根据具体某个程序做支持了……

**Comment by ivysrono** [comment]
原来是这样，我来看看 DoubleCommander 能不能自定义查看器。

**Comment by xkonglong** [comment]
不用搞成插件也行啊.  比如选项里开启对everything的支持, 则捕获到everything时, 采取复制路径然后开启的办法.   而对于dops, 我记得seer是支持的.

**Comment by xupefei** [comment]
I found that Everything provide such interface. I will look into it soon.
https://www.voidtools.com/support/everything/sdk/ipc/

**Comment by xkonglong** [comment]
great!

**Comment by xupefei** [comment]
已修复。
DOpus 开放的 dopusrt.exe 完全就是给小白用的东西，又笨又慢。
