### ISSUE TITLE
The app doesn't use dark theme in most cases

### ISSUE THREAD

**Issue by Kenya-West** [xupefei/QuickLook#298]
**Describe the bug**
When Windows 10 dark theme is enabled, QuickLook applies dark theme only at images. Rest file types are ignored, and QuickLook opens in light theme.

**To Reproduce**
1. Enable Windows 10 dark theme in Settings app
2. Click on any image. QuickLook will open it in dark
3. Click on any file except images (choose PDF, DOCX or folder, for example), QuickLook will open in light theme. 

**Expected behavior**
QuickLook opens in dark theme at any file type

**Desktop:**
 - OS Version: Windows 10 1803
 - QuickLook Version: 0.3.5 from Microsoft Store

**Screenshots and Exception Log**

![ezgif-2-c78ceb812b 1](https://user-images.githubusercontent.com/12271104/43044532-819d3952-8de2-11e8-94ca-a038426ace81.gif)

**Comment by xupefei** [comment]
The latest Nightly version already got this feature. Try it out :)

**Comment by 1111Al** [comment]
For me the dark theme on text files, has never worked, it always opens them in light theme.
