### ISSUE TITLE
BMP images are not shown

### ISSUE THREAD

**Issue by gigios** [xupefei/QuickLook#3]
I have tried to open a preview on some images but, for the 'bitmap' images, the QuickTool shown only the file information and not the image as for the jpg or png files.

**Comment by xupefei** [comment]
Do you mind uploading the image so I can have a look?

**Comment by gigios** [comment]
[1-10-2017.zip](https://github.com/xupefei/QuickLook/files/969748/1-10-2017.zip)

(The GitHub does not support directly the upload of bitmap)
The image is a portion of a full image download from Bing (used on my PC as desktop background). I have cut the image to reduce the size but I have the same problem also with all the original images.

**Comment by gigios** [comment]
Thanks, perfect! Now works!
