### ISSUE TITLE
Show folder inside in preview

### ISSUE THREAD

**Issue by iKenshu** [xupefei/QuickLook#31]
Hello!

I think that instead of showing the last modified on a folder, should show the inside of the folder and maybe navigate. 

_PS: Sorry for the english I'm Venezuelan_

**Comment by xupefei** [comment]
Sorry, this will not be considered. QuickLook aims to bring you a *minimum* and *simplified* experience, while listing all files gives too much information to users. Anyway you can always hit the ENTER key and preview again.
