### ISSUE TITLE
预览文件时出现错误

### ISSUE THREAD

**Issue by MsgnKyle** [xupefei/QuickLook#32]
系统：win7 x86
预览文件时点击空格之后出现如下错误：
![image](https://user-images.githubusercontent.com/29535324/27276029-58a13810-550c-11e7-986d-f0865e2387d4.png)

**Comment by xupefei** [comment]
你预览什么文件出现的错误？

**Comment by MsgnKyle** [comment]
只要预览文件就会出现错误

**Comment by xupefei** [comment]
你下载的是 .zip 包？

**Comment by MsgnKyle** [comment]
一直用的是msi文件安装的，上周五出现的这个问题，然后使用的zip文件，也是同样的问题

**Comment by xupefei** [comment]
你有没有装 .net 4.62的框架？https://www.microsoft.com/net/framework/versions/net462?source=dotnet

**Comment by MsgnKyle** [comment]
没有，是4.5的框架。

**Comment by xupefei** [comment]
4.5 框架运行似乎会报这个错误。
启动的时候没有提示吗？看来我需要强制提示一下。

**Comment by MsgnKyle** [comment]
没有提示，而且原来一直用着挺好的，从上周五才出现的这个问题

**Comment by xupefei** [comment]
是不是 0.2 版才开始报错？
你再装一下，https://github.com/xupefei/QuickLook/releases/tag/0.1.14 ，可以用吗？

**Comment by MsgnKyle** [comment]
应该是从0.2.0开始的，我看有更新就装了，然后就这样了

**Comment by MsgnKyle** [comment]
应该是从0.2.0开始的，我看有更新就装了，然后就这样了，请稍等，我现在下载一下0.1.14，我这边网速比较忙

**Comment by MsgnKyle** [comment]
十分感谢！
更新.net框架为4.62解决了问题！

**Comment by xupefei** [comment]
看来我需要强制一下了。

**Comment by 6e6e6e** [comment]
Win 10 x64 1703版本，.Net 4.7，QuickLook 0.2.1报一样的错误

**Comment by xupefei** [comment]
你系统里只有 4.7？

**Comment by xupefei** [comment]
我用虚拟机装了个win10 1703，没有报任何错误。
新装的系统里 HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP Release项的值是460798，是NET 4.7 （https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed）。

**Comment by 6e6e6e** [comment]
是只有4.7，之前装的0.2.0版本没有问题，更新到0.2.1版本才报错的

**Comment by 6e6e6e** [comment]
另外今天试了下卸载重装，看gif/jpg哪怕office都没问题，但预览过markdown就开始崩溃报错

**Comment by xupefei** [comment]
我又试了试，还是没有问题…0.2.1 其实也没改什么东西啊……
你现在再装回 0.2.0 还能用吗？如果能，
请 
1）安装 0.2.1，把 0.2.0 的 `QuickLook.Plugin.HtmlViewer.dll` 覆盖到 0.2.1 的相同文件上。
入果还是不能用，那么就
2）安装 0.2.1，把 0.2.0 的 `QuickLook.Native32.dll`，`QuickLook.Native64.dll`，`QuickLook.WoW64HookHelper.exe`三个文件覆盖到 0.2.1 的文件上。
上面的文件可以从 0.2.0 的 .zip 包里获得。

**Comment by 6e6e6e** [comment]
试了你说的方法，还是不行，可能是解析markdown哪里有问题吧

**Comment by xupefei** [comment]
随便看一个HTML正常么？

**Comment by 6e6e6e** [comment]
html正常，但是md和txt会报错

**Comment by xupefei** [comment]
神奇。md 和 txt 完全是两套预览插件。

**Comment by 6e6e6e** [comment]
简单的txt和md都还好，貌似长一点的就会报错，难不成跟路径有关？

**Comment by xupefei** [comment]
有可能。路径多长？

**Comment by 6e6e6e** [comment]
经过多次尝试，同样的文件，在桌面就可以预览，在别的文件夹预览就报错，应该是跟路径有关了，并不是路径长短的问题，我同样的文件，在桌面上新建个文件夹里面就预览不了

**Comment by xupefei** [comment]
你系统里有没有网络路径？

**Comment by 6e6e6e** [comment]
![default](https://user-images.githubusercontent.com/11614835/27397826-3ba3c798-56ea-11e7-996c-76ba7f8e23b7.png)

![default](https://user-images.githubusercontent.com/11614835/27397822-36cbcb6c-56ea-11e7-89a3-cbf651b01817.png)

**Comment by xupefei** [comment]
运行记事本，打开文件，定位到这个文件夹，选中这个css，空格。
能预览吗？

**Comment by 6e6e6e** [comment]
还是会崩溃 = =
![default](https://user-images.githubusercontent.com/11614835/27398017-eeea9e94-56ea-11e7-8ffa-fbc6a059dfd3.png)

**Comment by xupefei** [comment]
不不，我的意思是，在打开对话框中选中（单击）这个文件（不要真的打开），然后在打开对话框中按空格。

**Comment by 6e6e6e** [comment]
在打开里面空格预览是正常的
![default](https://user-images.githubusercontent.com/11614835/27442962-4bcda606-57a4-11e7-9d86-586817122fa8.png)

**Comment by xupefei** [comment]
看来你系统里有个COM组件坏掉了。
稍等我给你个带弹窗的DLL，你试试最多弹窗到哪里。

**Comment by 6e6e6e** [comment]
= = 重启电脑之后突然好了，现在直接预览也不崩溃了，好神奇

**Comment by 6e6e6e** [comment]
重启大法好，给微软跪了

**Comment by xupefei** [comment]
![m5503 0 ccp w19up 1a](https://user-images.githubusercontent.com/1687847/27443232-11da35c8-577b-11e7-862f-9245285af69e.jpg)
那等下次出问题的时候再说了……

**Comment by 6e6e6e** [comment]
哭笑不得

**Comment by xupefei** [comment]
@6e6e6e  上次你出问题的时候，是不是在桌面上没问题，在资源管理器窗口里就报错？
