### ISSUE TITLE
Crash on portable: Could Not Load Assembly: Operation not Supported (Exception from HRESULT: 0x80131515)

### ISSUE THREAD

**Issue by Cologler** [xupefei/QuickLook#33]
便携版本启动时会 crash 掉。

![picpick-20170621-152909-001](https://user-images.githubusercontent.com/10906962/27372211-618957b0-5696-11e7-9784-48d1329e5c66.png)

**Comment by xupefei** [comment]
#1.
请尽量使用安装版本。

**Comment by Cologler** [comment]
噢，解锁 zip 文件就可以解决了。
唉，主要是 msi 安装包会残留所以才不想安装。
