### ISSUE TITLE
Support .msg file 

### ISSUE THREAD

**Issue by m00nlygreat** [xupefei/QuickLook#36]
Hello! Thanks for your great work on QuickLook

It's awesome and making my work done much faster than before

I'm not a github user nor am I a developer just signed up to write this

So I don't know If I'm doing well but I just want to ask you for the support for .msg file that's used on Outlook. It would be great help for me and other fans of this project

Sorry for my poor English and Sorry If I was rude or I've tried an inappropriate contact

THANK YOU VERY MUCH

**Comment by xupefei** [comment]
note for myself: https://github.com/Sicos1977/MSGReader

**Comment by Sicos1977** [comment]
:+1:

**Comment by Sicos1977** [comment]
I also build something similar for vCards (contact cards) --> https://github.com/Sicos1977/VCardReader
