### ISSUE TITLE
crash on ???

### ISSUE THREAD

**Issue by Cologler** [xupefei/QuickLook#37]
![picpick-20170701-184709-001](https://user-images.githubusercontent.com/10906962/27761401-ca89d560-5e8d-11e7-9c2c-7e2f6c56dd85.png)

便携版。启动没啥问题，在任意地方按空格就会崩溃。奇怪的是前几天打开的时候一点问题都没有。

建议：

``` cs
AppDomain.CurrentDomain.UnhandledException += (sender, args) =>
            {
                MessageBox.Show(((Exception) args.ExceptionObject).Message + Environment.NewLine +
                                ((Exception) args.ExceptionObject).StackTrace);

                Shutdown();
            };
```

这里把异常类型打印出来。看输出内容应该是 `TargetInvocationException` 异常，这个异常有内部异常的。

又及，我的 VS 2017 无法编译，我就不改了（逃

**Comment by xupefei** [comment]
https://github.com/xupefei/QuickLook/issues/32

**Comment by Cologler** [comment]
After installed 0.2.2, it show the message:

![picpick-20170706-230341-001](https://user-images.githubusercontent.com/10906962/27917713-68506164-629f-11e7-8486-aeb0e41b5ecc.png)

**Comment by xupefei** [comment]
选定的这个文件路径有多长?

**Comment by Cologler** [comment]
超短，d:\E02AD11FB45ED3537157E301D09740B7.gif

**Comment by xupefei** [comment]
上次 #32 里也是类似的情况。试过重启吗？

**Comment by Cologler** [comment]
重启是能解决，总觉得有什么不对。

**Comment by xupefei** [comment]
你出问题的时候，是不是只在资源管理器窗口里报错？桌面上没问题？

**Comment by Cologler** [comment]
@xupefei 这个不清楚，我桌面没文件。。。而且挺久没遇上这个 bug 了。
