### ISSUE TITLE
Blur transparency?

### ISSUE THREAD

**Issue by charlesmilette** [xupefei/QuickLook#41]
Kinda like WinQuickLook does, with the SetWindowCompositionAttribute undocumented API on Windows 10, and DwmEnableBlurBehind in earlier versions.

**Comment by xupefei** [comment]
But QuickLook is already doing this: https://github.com/xupefei/QuickLook/search?utf8=%E2%9C%93&q=SetWindowCompositionAttribute&type=

**Comment by charlesmilette** [comment]
Woooops my bad
