### ISSUE TITLE
Audio not playing

### ISSUE THREAD

**Issue by xupefei** [xupefei/QuickLook#42]

**Comment by gloomy-ghost** [comment]
![default](https://user-images.githubusercontent.com/13086421/28767483-f245aeec-7627-11e7-9ad6-63b96873951a.png)

Reopen?

**Comment by xupefei** [comment]
The new FFME player is not very stable. Please kill the process and try again.
I am currently looking for a replacement. Sorry for the annoyance.

**Comment by gloomy-ghost** [comment]
It seems that it is always reproducible for me... Is there a debugging version so that I can provide some detailed logs?

**Comment by xupefei** [comment]
Thank you but it's not needed. I know where is the problem.
I will make a replacement in a few days.

**Comment by xupefei** [comment]
Fixed in 0.2.5.
