### ISSUE TITLE
Exception: Target Invocation when trying to preview a file

### ISSUE THREAD

**Issue by tralston** [xupefei/QuickLook#44]
Windows 7 SP1 x64. 
After a fresh installation, I tried to preview a number of different file types (txt, doc, pdf) and they all resulted in an exception being thrown.

![image](https://user-images.githubusercontent.com/348697/28548823-0af0ab38-708b-11e7-95d9-18b7c2287d7f.png)

**Comment by xupefei** [comment]
Does a reboot helps?

**Comment by xupefei** [comment]
Hi, could you tell me 
1) is it okay when previewing a file from the Desktop?
2) is it crashed when previewing a file from the File Explorer window?

**Comment by tralston** [comment]
Ah, I think your onto something. I tried it from my Desktop and it worked
fine. Then I opened a File Explorer window, showing the Desktop folder and
it didn't work on the same files.

**Comment by tralston** [comment]
Ah, I think your onto something. I tried it from my Desktop and it worked fine. Then I opened a File Explorer window, showing the Desktop folder and it didn't work on the same files.

**Comment by xupefei** [comment]
Thanks for your reply. Could you try these two files? You may need to quit QuickLook before overwriting them.

[QuickLook.Native-44.zip](https://github.com/xupefei/QuickLook/files/1181342/QuickLook.Native-44.zip)

**Comment by tralston** [comment]
Well, I don't get the original error message anymore, I get another one.

![image](https://user-images.githubusercontent.com/348697/28693775-46c5c10a-72db-11e7-8e22-1f4c3889c5bc.png)

**Comment by xupefei** [comment]
Sorry, I put the wrong file. Should be this: https://github.com/xupefei/QuickLook/files/1181349/QuickLook.Native-44-2.zip

**Comment by tralston** [comment]
That seems to work now. Thank you!

**Comment by xupefei** [comment]
Glad to hear that. Therefore this bug fix will be shipped with the next
release, maybe in this weekend. For now you may continue to use these DLLs,
or download the nightly version from AppVeyor (links in the front page.)

Cheers,
Paddy
