### ISSUE TITLE
稍大psd文件无法预览

### ISSUE THREAD

**Issue by Longxr** [xupefei/QuickLook#48]
psd文件是有大小或者尺寸限制么，齿轮消失后还是一片白，5MB以上的文件

**Comment by xupefei** [comment]
给个样本？

**Comment by Longxr** [comment]
https://pan.baidu.com/s/1hrPpM3U 这里面的psd都不能预览

**Comment by Longxr** [comment]
还有一个问题，这个软件只能在默认的资源管理器使用么，[clover](http://cn.ejie.me/)打开的资源管理器空格键无效

**Comment by xupefei** [comment]
Clover 可能把窗口的特征值改了。请另外开一个 issue :)

**Comment by Longxr** [comment]
好的

**Comment by xupefei** [comment]
我试了试，就算是原版ImageMagick也搞不定这些文件，估计是ImageMagick不支持灰色单通道。
这问题我无法修复，是上游的问题了。
