### ISSUE TITLE
Huge memory usage

### ISSUE THREAD

**Issue by vhanla** [xupefei/QuickLook#49]
After a while it takes a lot of memory. I don't know what is really causing it, I just viewed GIF files, MP4s, markdown, etc. I don't really know what caused it.

![capture](https://i.imgur.com/0Ifxusy.png)

**Comment by xupefei** [comment]
Gif image sometime causes memory leak. I am now working on a fix.

**Comment by xupefei** [comment]
I just uploaded a new version 0.24. You may have a try.

**Comment by xupefei** [comment]
Fixed in 0.2.5.
