### ISSUE TITLE
DOCX and PPTX managed as Zip file in the preview instead the correct 'office' preview

### ISSUE THREAD

**Issue by gigios** [xupefei/QuickLook#5]
On my PC I have installed the Office 2016.
When I try to shown the preview on a PowerPoint file (pptx) the QuickLook shown in the preview the 'content' of the file instead the 'correct' preview.
The same problem with a Word document (docx)
If I try to save the PowerPoint in the old ppt format (PowerPoint 97-2003) the preview shown the file information.

I don't know if this is the current 'visualization' because it's a Work In Progress or if it's a real bug.

**Comment by xupefei** [comment]
I found that for some reason the OfficeViewer plugin is not included in the release package. I will fix it.

**Comment by xupefei** [comment]
Fixed in 863046ff55dd2fe2f5447103cb50ebca8915f732 and in v0.1.2.

**Comment by gigios** [comment]
Thanks, now Word works in the correct way. For the PowerPoint there is only a 'dirty effect' related to the visualization of the full PowerPoint app before show the preview (probably because it's necessary to 'render' the pptx to show in the preview).
