### ISSUE TITLE
New UI icons set to match the Fluent Design Language

### ISSUE THREAD

**Issue by OiCkilL** [xupefei/QuickLook#51]
图标选得有点粗，跟win10的风格不是很搭，推荐换细点的图标。
有需要的话，我可以提供一套设计

**Comment by xupefei** [comment]
好哇，求设计。
最好是有两个版本，在win7下的黑边白线，和在win10上的纯白线（类似openvpn客户端那种）。

**Comment by OiCkilL** [comment]
@xupefei 把需要的图标列一下吧，我出套svg格式的给你

**Comment by xupefei** [comment]
好，我明天列个表。

**Comment by xupefei** [comment]
I believe the UI icons you provided in #56 are perfect matching the Fluent design. New icons stilled needed are 
1) Application executable icon (for Windows 7 and Windows 10 respectively)
2) Video/audio player control buttons.

**Comment by xupefei** [comment]
Fixed in #67.
