### ISSUE TITLE
对seer的处理

### ISSUE THREAD

**Issue by EMLVIRUS** [xupefei/QuickLook#52]
已经收到关于seer违反GPL的消息，因此希望告知如何处理我组织的awesome list列出的seer

**Comment by xupefei** [comment]
别急……

**Comment by xupefei** [comment]
作者最终遵守 GPL 协议把 1.5.0 版本开源了。Awesome list 那边没必要去掉了。

**Comment by JokerQyou** [comment]
Seer 好像已经把代码库清空了，不再能够找到 1.5.0 版本的源代码。现在 Seer 仓库仅作为 bug report 使用。

**Comment by xupefei** [comment]
https://github.com/xupefei/Seer/tree/master/1.5.0
