### ISSUE TITLE
0.2.4 zip版打不开

### ISSUE THREAD

**Issue by OiCkilL** [xupefei/QuickLook#53]
提示以下错误，只有把插件目录清空才能运行。里面有任何一个插件都会提示类似错误，我在使用Mactype，不知道是否有关系
![20170801010414](https://user-images.githubusercontent.com/613988/28789518-55033b0a-7658-11e7-86e5-b3d80d7709af.png)

**Comment by xupefei** [comment]
See #1.
解压前先解锁。
