### ISSUE TITLE
Redesigned The QuickLook UI for Fluent Design System

### ISSUE THREAD

**Issue by OiCkilL** [xupefei/QuickLook#56]
重新设计了下，为了符合 Fluent Design System
![artboard 2](https://user-images.githubusercontent.com/613988/28860237-4e30b9ce-778e-11e7-95c0-d116961256ff.png)

**Comment by xupefei** [comment]
漂亮爆了。

我有几个问题：
1. 标题栏的透明是相对于内容的，而不是相对于窗口下面的颜色？也就是说，窗口本身不透明？
2. 在窗口被固定之后，是不是给固定按钮加一个背景色会更加明显一些？

**Comment by xupefei** [comment]
One more question, should the title bar be able to auto-hide, and only appears when mouse approached?

**Comment by OiCkilL** [comment]
1. Yes, you are right. The preview window in fact is not transparent.
2. I'm optimizing this design.
3. I think auto-hide only in media window is better.

**Comment by OiCkilL** [comment]
Update, about audio and video.
![artboard 2](https://user-images.githubusercontent.com/613988/28913309-201117be-786a-11e7-9d22-8b2483a544ab.png)

**Comment by xupefei** [comment]
Good work, they are truly impressive.

I'm now fighting with a HLSL shader for blur effect (as in your mockup). I hope I can get something today in the evening.

**Comment by xupefei** [comment]
Finally I got managed the blur effect (with noise layer.) It uses 2-passes GPU rendering therefore it should be fast enough.
![blur](https://user-images.githubusercontent.com/1687847/28945315-ab1c0a14-78ae-11e7-961b-4c200937e04e.png)

**Comment by xupefei** [comment]
Hi, could you send me the PSD file as well as the new UI icons? I want to find some detailed design with it as well as tweaking new icons.

**Comment by OiCkilL** [comment]
I can give you an .sketch or pdf file. You may open the .sketch file in Mac.

**Comment by xupefei** [comment]
Excellent. you may send it via email at xupaddy#gmail#com.

Thanks for the work!

**Comment by xupefei** [comment]
Now the new UI design comes into shape, although still lots of work to do:

![20170806](https://user-images.githubusercontent.com/1687847/29006778-1eaa5196-7aff-11e7-81c8-db0ee520ad8b.png)

**Comment by QubitsDev** [comment]
Hello, I like this project, I had done some interface designs for Quicklook in Fluent Designs but the ones that posted are better.
Also design some icons and tiles for windows 10
If you are interested, I can send the Illustrator files with the icons...
## Regular Icon (Ico format)
![quicklook icon_128](https://user-images.githubusercontent.com/25881789/29105019-01325984-7c98-11e7-9d23-1fb94c23339d.png)
## Windows 10 Tiles (PNG)
![quicklooktiles_smalltile](https://user-images.githubusercontent.com/25881789/29105084-89901a00-7c98-11e7-8721-5f8b042a719a.png)
![quicklooktiles_mediumtile](https://user-images.githubusercontent.com/25881789/29105088-8b262f4e-7c98-11e7-8850-4aa7a9804077.png)
![quicklooktiles_widetile](https://user-images.githubusercontent.com/25881789/29105089-8d54a138-7c98-11e7-8584-371cf35d9d74.png)

**Comment by xupefei** [comment]
![image](https://user-images.githubusercontent.com/1687847/29146141-74957962-7d68-11e7-949d-950ea3ebb2ec.png)

Looks good :)

@QubitsDev Thanks for the beautiful icon! I would like to use it in the next release.
One comment is that, the regular icon seems not fit with other icons in Windows OS. Maybe removing the gradient will be better?

**Comment by QubitsDev** [comment]
@xupefei Thank you for approving my design.
Following your comment remove the gradient of the Regular Icon and I made two versions.
### Blue Version
![quicklook icon - blue_128](https://user-images.githubusercontent.com/25881789/29154354-ec0356f6-7d61-11e7-8807-a22acc384baf.png)
### Purple Version
![quicklook icon - purple_128](https://user-images.githubusercontent.com/25881789/29154356-f0414b10-7d61-11e7-8dda-f34754f9895e.png)
I also made a White version for the tray.
### Tray Icon (Mockup)
![uwpapptemplate_13- laptop](https://user-images.githubusercontent.com/25881789/29154414-8363530c-7d62-11e7-8414-f6581afe5c55.png)
All designs are made in Adobe Illustrator.

Can I send the files by E-mail or post them here?
I can also send them in PNG format for the tiles and ICO Format for regular icon.

**Comment by xupefei** [comment]
@QubitsDev Yes, you may send them to me via email: xupaddy#gmal#com.
BTW, have you tested the white and blue/purple icon at the size 16x16, which is for "normal" 100% Dpi screens?

**Comment by QubitsDev** [comment]
**I already sent the files**
- The Ico files have all the sizes (16 px, 24 px, 32 px, 48 px, 64 px, 96 px, 128 px, 256 px, 512 px, 768 px)
- The tiles have all sizes and scale (100%, 125%, 150%, 200%, and 400%)
- Also includes tray icons in white and black.
- I Include Illustrator files in case you want to make a modification.

**Comment by xupefei** [comment]
Icons have been updated in e4ab7d0a321f07a013e98a7281efb0de167b8f2d and 1d7c95a82204a1bed7571de7b26f18a93fdc1f25.

**Comment by codesharkasm** [comment]
The share menu does not open the share menu. This would be useful, but it only opens the "open with" panel. Please fix!

**Comment by TaicEart** [comment]
在 win8.1 上有一个问题：托盘图标是全白的，因此在收入隐藏托盘时在白色背景上完全看不到。可以给 16px 加上类似默认图标的勾边吗？或者我来改画一个？

**Comment by xupefei** [comment]
@TaicEart 这类问题还请新开一个 issue 以便于跟踪
