### ISSUE TITLE
切换预览多个小尺寸图片时, 预览窗口会右移

### ISSUE THREAD

**Issue by 3ny92** [xupefei/QuickLook#58]
windows 10 专业版
版本 1703
os版本 15063.413
QuickLook版本 0.2.0
使用系统的文件资源管理器预览小尺寸图片时, 切换预览图片(我使用的图片尺寸为124x124, 大图片上未发现该问题)会使预览窗口右移很多, 直至预览窗口移出屏幕
预览文件夹时, 反复切换会使预览窗口向左上微移

**Comment by xupefei** [comment]
Same as #50.
