### ISSUE TITLE
File Info: Icon visualization is wrong! Too big

### ISSUE THREAD

**Issue by gigios** [xupefei/QuickLook#6]
First of all, this is only a visualization problem and not a blocking error.
If I select, for example, an EXE, the preview shown is the 'File Info' preview (and this is ok).
The problem is that the icon shown is always (I have tried with many different files type) too big.
![immagine](https://cloud.githubusercontent.com/assets/8749627/25693777/7af91ba6-30ab-11e7-905a-e5f56f237f47.png)
In the screenshot sample I have used the regedit.exe as 'test'.

Version: v0.1.2
PS: The exe version is always 1.0.0.0

**Comment by xupefei** [comment]
This is already fixed in 689a3a78781724a48380e8b1fd7a20ae7cc02d51.
My testing is all on high DPI device, so I haven't see this till yesterday.

**Comment by gigios** [comment]
Ok! Sorry, I haven't seen the fix.
