### ISSUE TITLE
固定窗口功能

### ISSUE THREAD

**Issue by S7venYoung** [xupefei/QuickLook#62]
目前pin功能只是不让预览窗口消失，可以考虑一下直接最前台显示呢？

**Comment by xupefei** [comment]
Not pinned:
![image](https://user-images.githubusercontent.com/1687847/29190737-e49dda04-7e23-11e7-9b41-bf05b6490feb.png)
Pinned:
![image](https://user-images.githubusercontent.com/1687847/29190747-ee82b3f0-7e23-11e7-9ea7-0b1d8b1dad8f.png)
Pinned & TopMost
![image](https://user-images.githubusercontent.com/1687847/29190756-f2b13b68-7e23-11e7-8b08-8e5b63d5c426.png)

Fixed :)
