### ISSUE TITLE
Resizing QL window creates blur that persists between previews

### ISSUE THREAD

**Issue by tralston** [xupefei/QuickLook#66]
Windows 7 x64 SP1, Aero Glass on

When starting a quicklook preview, if you resize the preview window, it "draws" a blurry aero glass area around the new window size. If resize continually or multiple times, it remembers the "composite" shape of all previous sizes (which sometimes extends beyond the current preview window). This area blurs the background. You still can interact with whatever's behind the blur. This persists between previews. It does not persist after quitting and restarting the quicklook program.

See animation. Blur is located to right and below preview window.
![quicklook-blur](https://user-images.githubusercontent.com/348697/29193693-411b2afa-7ddb-11e7-92e5-c7dd62b43074.gif)

**Comment by xupefei** [comment]
It will be fixed in the next release - because the blur has been removed!

cheers,
Paddy
