### ISSUE TITLE
make the title bar transparent，or auto hide

### ISSUE THREAD

**Issue by fan-cy** [xupefei/QuickLook#69]
0.3.0版本中，只有预览音频格式时，标题栏与内容区域色彩保持一致。希望其他文件预览时也能这样，使用透明菜单栏，或者改为打开时隐藏标题栏，鼠标移动到标题栏位置再显示。
尤其是图片格式，现在是打开时显示标题栏，几秒钟后自动隐藏，这样标题栏会挡住图片顶部显示的内容。

**Comment by xupefei** [comment]
I have changed to auto-hide time from 3 to 1 second. It now feels better (download it from [here](https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts) if you want.)

Regarding your suggestion that “auto-hide title bar for all viewers”, the option from the designer (and I) is that it should be only in multimedia previews: #56.

**Comment by xupefei** [comment]
Fixed in 59d957f06cd5249a1fe0fe35a23f24befdb06e19.
