### ISSUE TITLE
Does not work for excel documents

### ISSUE THREAD

**Issue by JokerQyou** [xupefei/QuickLook#7]
When pressing space key on an `xlsx` file, a preview window with loading animation will popup, and then Excel itself will open a 'Save as' dialog. Also if you do some other things (like click on the preview window then press the space key, or just simple leave the 'Save as' dialog open and wait for QuickLook to respond), QuickLook will crash with an error message.
![image](https://cloud.githubusercontent.com/assets/1465267/25832000/658c2072-349a-11e7-88b8-fc56825c8075.png)

Software version: Excel 2016, QuickLook v0.1.5. 

PS. You have the version string `1.0.0.0` set in the file `QuickLook.exe`, but the actual software version is `0.1.5`, that might be confusing to some users.

**Comment by xupefei** [comment]
May you compile and try the latest version?
Now it should show a information window instead of throwing a error.

Regarding the version number, I am still thinking how to link it to a git tag, since the releases are created automatically by AppVeyor when a new tag is pushed to GitHub.

**Comment by JokerQyou** [comment]
I'm not sure if I have the development environment setup on my Windows computer, I'll check that tomorrow. You can use `git describe --tags` to get the tag name after checking out a tag.

**Comment by xupefei** [comment]
Thanks for the reply. I have upload the binary to github. You can try it
now.

Paddy

**Comment by JokerQyou** [comment]
Hmm, I've tried v0.1.6, and it did not crash so far, but Excel is still opening the 'Save As' dialog. If you manually close the dialog, QuickLook will be able to show render the preview, but the font is very small.

![image](https://cloud.githubusercontent.com/assets/1465267/25978274/ab2eedfc-36f3-11e7-8f60-e8fdc8e20adb.png)

**Comment by xupefei** [comment]
May you upload a screen capture of that "save as" dialog? I never seen it.

**Comment by JokerQyou** [comment]
![image](https://cloud.githubusercontent.com/assets/1465267/26048526/121b4bf8-398a-11e7-9683-9146d61e01ce.png)

**Comment by xupefei** [comment]
Strange. The file should be exported as a .pdf, not .xlsx anymore.
Has this file be [locked](http://www.chilkatforum.com/questions/8260/could-not-load-assembly-operation-not-supported-exception-from-hresult-0x80131515)?
Is it convenient for you to upload this file?

**Comment by JokerQyou** [comment]
No, I can confirm this file is not locked. And sorry I could not upload this file although there's nothing secret in it.

This file has `.xls` extension, and is in has multiuserediting enabled. Maybe that is the root cause. I just created an empty `.xlsx` file and save it as `.xls` extension, and enabled multiuserediting, and was able to reproduce this issue right away.

**Comment by xupefei** [comment]
Thanks for the reply. I can now reproduce it as well.
However I did not find any solution to this - The Office COM is rather poorly written.

**Comment by xupefei** [comment]
The issue should be solved from version 0.1.10. Can you confirm it?
