### ISSUE TITLE
allow dark mode for viewing transparent/white png files

### ISSUE THREAD

**Issue by jgarza9788** [xupefei/QuickLook#70]
http://imgur.com/NE0BrBh

it's so very difficult to find the right image like this >.<

**Comment by xupefei** [comment]
You may try to add a button somewhere in the window for switching light/dark background.

**Comment by demolitionb** [comment]
What's the current status? The check board pattern in my case is very dark and I can not recognize black text on transparent background.

**Comment by xupefei** [comment]
It’s still haven’t be done.
I have been busy working on other work for months and have no enough time on this project. Hopefully I can finish my work in two months and go back to deal with the blasted open issues.

cheers,
Paddy
