### ISSUE TITLE
预览 Gif 文件出现类似花屏的效果

### ISSUE THREAD

**Issue by S7venYoung** [xupefei/QuickLook#78]
预览 Gif 文件，画面完全撕裂，动图花屏

**Comment by xupefei** [comment]
应该是差分帧的问题。能提供相应的 GIF 文件用来测试么？

**Comment by S7venYoung** [comment]
![auto](https://user-images.githubusercontent.com/8165400/29906081-274a6418-8e45-11e7-9485-bf7a5c700a11.gif)
