### ISSUE TITLE
.exe gets deleted after install

### ISSUE THREAD

**Issue by jgarza9788** [xupefei/QuickLook#79]
https://drive.google.com/open?id=0Bwcx81B943RxSDAxMjQ0a1NsLTA
^a gif

the .exe file gets made during install 
but right after it gets deleted?!?!

--optional 
you could provide a .exe (portable version of the program/app)

THANKS!

**Comment by xupefei** [comment]
It looks like the installer have deleted it. Sometime MSI installer do weird things.
