### ISSUE TITLE
Window on front

### ISSUE THREAD

**Issue by emannxx** [xupefei/QuickLook#81]
At some point during the early development, the preview window always showed up on top of everything else (as, in my opinion, it should). However, a while ago, this behavior has changed and it no longer stays on top.

I think it'd be best to give the user the option to show QuickLook's window on top **by default** or not (without having to use the pin-button). In my specific case, I find it better to keep it distinguished from all other windows, by keeping it the topmost window.

**Comment by xupefei** [comment]
I am planning to give a option about this. However I am quite busy on other works (you may already noticed that the project has stopped for some days) so it will not be very soon.

I should be back to development in the next month. At that time the mentioned feature will be added.

cheers,
Paddy

From: Emanuel Alves
Sent: 04 September 2017 20:07
To: xupefei/QuickLook
Cc: Subscribed
Subject: [xupefei/QuickLook] Window on front (#81)

At some point during the early development, the preview window always showed up on top of everything else (as, in my opinion, it should). However, a while ago, this behavior has changed and it no longer stays on top.
I think it'd be best to give the user the option to show QuickLook's window on top or not. In my specific case, I find it better to keep it distinguished from all other windows, by keeping it the topmost window.

**Comment by emannxx** [comment]
Awesome! 👍

**Comment by xupefei** [comment]
Fixed in db9111ff220eea80c202e5d81808ee756097ebc0.
