### ISSUE TITLE
Windows 7 x64 Explorer not working

### ISSUE THREAD

**Issue by Sam1ive** [xupefei/QuickLook#85]
Not working in windows explorer. Desktop its working preview files

**Comment by xupefei** [comment]
There was once a bug which cause your problem, and was fixed in one recent
release. Are you on the latest version?

**Comment by feldrim** [comment]
I'm using v0.3.1, which is the most recent by the day, on Windows 7 Professional x64 and still can't look inside the folders. I can only see properties of the folder, not the things inside.

**Comment by reelism** [comment]
Same issue here, using tabbed explorer app Clover, latest portable version.

**Comment by xupefei** [comment]
Windows 7+Clover+QuickLook is known incompatible. You have to pick one from Clover and QuickLook, or just upgrade to Windows 10.
