### ISSUE TITLE
软件很棒扩展插件应该怎么写?

### ISSUE THREAD

**Issue by harry3633** [xupefei/QuickLook#87]
刚刚用，软件很棒。
发现可以用插件来增加功能，应该怎么写？如果大家都能添加的话，那预览的文件种类就很庞大了。
我是做硬件设计的，希望能预览各种pcb文件，不知道实现容易不。
谢谢！

**Comment by xupefei** [comment]
首先你得先找到一个 pcb 转图片或 pdf 的库，然后在你的插件里调用它。这之后，你可以直接调用现有的 pdf 或图片预览插件来预览你转出来的文件。
一个例子：Markdown 的预览器里调用了 HTML 预览器：https://github.com/xupefei/QuickLook/blob/master/QuickLook.Plugin/QuickLook.Plugin.MarkdownViewer/Plugin.cs

**Comment by harry3633** [comment]
谢谢，研究一下
