### ISSUE TITLE
QuickLook会占用原文件，无法删除或自动更新预览

### ISSUE THREAD

**Issue by kenkangxgwe** [xupefei/QuickLook#92]
经常会通过QuickLook来观察输出结果，但是由于QuickLook会占用文件，导致无法写入，（有时候关闭QuickLook窗口后台也会占用，必须任务管理器结束进程）必须关闭QuickLook后才能写入。希望能够改善，感谢这么好的软件！

**Comment by xupefei** [comment]
这个文件是不是很大？

**Comment by kenkangxgwe** [comment]
并不是，只是几百k的图片而已

**Comment by emc2314** [comment]
我这边也是这个问题, 一个json文件预览之后关掉, 就无法修改保存了.
