### ISSUE TITLE
是否有计划支持xyexplorer

### ISSUE THREAD

**Issue by tianzhijiexian** [xupefei/QuickLook#96]

**Comment by xupefei** [comment]
XYplorer 使用空格键作为搜索关键词的一部分，如果 QuickLook 想要预览的话就会和它冲突。
请在 XYplorer 中自定义一个快捷键来呼出外部程序。调用  QuickLook 的语法是 `QuickLook.exe C:\path\to\your\file.txt`。

**Comment by tianzhijiexian** [comment]
谢谢！！！！

**Comment by WaveF** [comment]
挖个坟...创建一个内容如下xys后缀的脚本：
`run "C:\Users\wavef\AppData\Local\Programs\QuickLook\quicklook.exe" "<curitem>";`

然后在菜单“用户”-“管理命令”下创建一个新命令指向此脚本，并绑定一个快捷键，就可以用quicklooke来预览了

**Comment by MOOA-code** [comment]
> 挖个坟...创建一个内容如下xys后缀的脚本：
> `run "C:\Users\wavef\AppData\Local\Programs\QuickLook\quicklook.exe" "<curitem>";`
> 
> 然后在菜单“用户”-“管理命令”下创建一个新命令指向此脚本，并绑定一个快捷键，就可以用quicklooke来预览了

![image](https://user-images.githubusercontent.com/54346272/82542897-56f3df00-9b85-11ea-9761-a553ba0388fc.png)
你好，按照你这方法可以是可以，但是会先弹出这个，应该怎么解决啊？

**Comment by sonicmingit** [comment]
> > 挖个坟...创建一个内容如下xys后缀的脚本：
> > `run "C:\Users\wavef\AppData\Local\Programs\QuickLook\quicklook.exe" "<curitem>";`
> > 然后在菜单“用户”-“管理命令”下创建一个新命令指向此脚本，并绑定一个快捷键，就可以用quicklooke来预览了
> 
> ![image](https://user-images.githubusercontent.com/54346272/82542897-56f3df00-9b85-11ea-9761-a553ba0388fc.png)
> 你好，按照你这方法可以是可以，但是会先弹出这个，应该怎么解决啊？

![image](https://user-images.githubusercontent.com/18570497/86261007-98e65b00-bbf0-11ea-99dc-4988fdfeccfb.png)
去掉脚本里的语法检查

**Comment by MOOA-code** [comment]
> > > 挖个坟...创建一个内容如下xys后缀的脚本：
> > > `run "C:\Users\wavef\AppData\Local\Programs\QuickLook\quicklook.exe" "<curitem>";`
> > > 然后在菜单“用户”-“管理命令”下创建一个新命令指向此脚本，并绑定一个快捷键，就可以用quicklooke来预览了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/54346272/82542897-56f3df00-9b85-11ea-9761-a553ba0388fc.png)
> > 你好，按照你这方法可以是可以，但是会先弹出这个，应该怎么解决啊？
> 
> ![image](https://user-images.githubusercontent.com/18570497/86261007-98e65b00-bbf0-11ea-99dc-4988fdfeccfb.png)
> 去掉脚本里的语法检查

谢谢，解决了

**Comment by alex89924** [comment]
> 

方便分享下这些步骤的详细操作吗？
感谢！
